function render_config() {
	let lldp = ubbf_get(config, 'Device.LLDP');
	let enable = ubbf_to_bool(lldp?.Enable);

	services.set_enabled('lldpd', enable);

	if (!enable)
		return;


	uci_named_section(output, 'lldpd.config', 'lldpd');
	uci_set_number(output, 'lldpd.config.lldp_class', 4);
	uci_set_string(output, 'lldpd.config.lldp_description', 'Internet Gateway');
	uci_set_string(output, 'lldpd.config.lldp_syscapabilities', 'router,bridge,wlan');
	uci_list_string(output, 'lldpd.config.interface', 'lan');
}
uci_comment(output, '# generated by lldp.uc');
render_config();
