function render_config() {
	const UMDNS_DIR = '/tmp/ubbf/umdns';

	/**
	 * Collects downstream interface names for mDNS service.
	 *
	 * @param {array} ip_interfaces - IP interface instances
	 * @returns {array} List of non-upstream interface names
	 */
	function collect_allowed_interfaces(ip_interfaces) {
		let allow = [];

		for (let iface in ip_interfaces) {
			if (!iface.Name)
				continue;
			if (ubbf_to_bool(iface.Upstream))
				continue;
			push(allow, iface.Name);
		}

		return allow;
	}

	/**
	 * Generates UCI umdns configuration section.
	 *
	 * @param {array} output - Output array to append to
	 * @param {array} networks - List of network names to enable
	 */
	function generate_umdns_config(output, networks) {
		uci_section(output, 'umdns umdns');
		uci_set_number(output, 'umdns.@umdns[-1].jail', 1);

		for (let network in networks)
			uci_list_string(output, 'umdns.@umdns[-1].network', network);
	}

	/**
	 * Generates a umdns service JSON object from advertise data.
	 *
	 * @param {object} advertise - DNS-SD advertise configuration
	 * @returns {object} Service object for umdns JSON file
	 */
	function generate_service_json(advertise) {
		// TR-181 states ApplicationProtocol without the leading underscore
		// and TransportProtocol as TCP or UDP; DNS-SD labels carry both
		// with one. A value that already has the underscore still works.
		let app = '_' + ltrim(advertise.ApplicationProtocol || 'http', '_');
		let trans = (uc(advertise.TransportProtocol ?? '') == 'UDP') ? '_udp' : '_tcp';
		let domain = advertise.Domain || 'local';
		let service_name = `${app}.${trans}.${domain}`;

		let service = {
			service: service_name,
			port: ubbf_to_int(advertise.Port) || 80,
		};

		if (advertise.InstanceName)
			service.instance = advertise.InstanceName;

		let text_records = ubbf_instances(advertise, 'TextRecord');
		let txt = [];
		for (let tr in text_records) {
			if (tr.Key && tr.Value)
				push(txt, `${tr.Key}=${tr.Value}`);
		}
		if (length(txt) > 0)
			service.txt = txt;

		return service;
	}

	/**
	 * Sanitises a name for use as a service identifier.
	 *
	 * @param {string} name - Name to sanitise
	 * @returns {string} Lowercase alphanumeric name with underscores
	 */
	function sanitise_id(name) {
		return replace(lc(name), /[^a-z0-9_]/g, '_');
	}

	let old_services = fs.lsdir(UMDNS_DIR);
	for (let f in old_services)
		fs.unlink(`${UMDNS_DIR}/${f}`);
	fs.mkdir(UMDNS_DIR, 0755);

	let sd = ubbf_get(config, 'Device.DNS.SD');
	if (!sd)
		return;

	let enabled = ubbf_to_bool(sd.Enable);
	services.set_enabled('umdns', enabled);

	if (!enabled)
		return;

	let ip_interfaces = ubbf_instances(config, 'Device.IP.Interface');
	let networks = collect_allowed_interfaces(ip_interfaces);

	generate_umdns_config(output, networks);

	let advertises = ubbf_instances(sd, 'Advertise');
	for (let adv in advertises) {
		if (!ubbf_to_bool(adv.Enable))
			continue;

		let service_id = sanitise_id(adv.InstanceName || `service_${adv['.instance']}`);
		let service_data = generate_service_json(adv);

		let json_content = {};
		json_content[service_id] = service_data;
		fs.writefile(`${UMDNS_DIR}/${service_id}.json`, sprintf('%.J\n', json_content));
	}

}
uci_comment(output, '# generated by umdns/render.uc');
render_config();
