function render_config() {
	/**
	 * Finds the UCI name of the IPv6 WAN interface to use as the tunnel
	 * source. The DS-Lite netifd proto uses the named interface's first
	 * IPv6 address as the tunnel local endpoint; without it the handler
	 * falls back to network_find_wan6(), which requires a tracked IPv6
	 * default route on an interface and fails silently on setups that
	 * only have on-link prefixes.
	 *
	 * @returns {string} UCI interface name (e.g. "wan6"), or '' if none
	 */
	function wan6_tunlink_resolve() {
		let ip_interfaces = ubbf_instances(config, 'Device.IP.Interface');
		for (let iface in ip_interfaces) {
			if (!iface.Name)
				continue;
			if (!ubbf_to_bool(iface.Upstream))
				continue;
			return `${iface.Name}6`;
		}
		return '';
	}

	/**
	 * Generates UCI network interface sections for DS-Lite tunnels.
	 *
	 * Each enabled InterfaceSetting produces a UCI network interface
	 * with proto=dslite. The netifd dslite.sh handler creates the
	 * IPv4-in-IPv6 tunnel, resolves the AFTR address, and adds NAT rules.
	 *
	 * @param {array} settings - DSLite InterfaceSetting instances
	 * @param {string} tunlink - WAN6 UCI interface name for tunnel source
	 * @returns {string} UCI batch output for dslite interfaces
	 */
	function generate_dslite(settings, tunlink) {

		for (let setting in settings) {
			if (!ubbf_to_bool(setting.Enable))
				continue;

			let name = sprintf('dslite_%s', setting['.instance']);

			let peeraddr = null;
			if (setting.EndpointAddressTypePrecedence == 'FQDN')
				peeraddr = setting.EndpointName;
			else if (setting.EndpointAddressTypePrecedence == 'IPv6Address')
				peeraddr = setting.EndpointAddress;
			else
				peeraddr = (setting.EndpointAddress && setting.EndpointAddress != '')
					? setting.EndpointAddress : setting.EndpointName;

			if (!peeraddr || peeraddr == '')
				continue;

			uci_named_section(output, `network.${name}`, 'interface');
			uci_set_string(output, `network.${name}.proto`, 'dslite');
			uci_set_string(output, `network.${name}.peeraddr`, peeraddr);
			uci_set_string(output, `network.${name}.zone`, 'wan');
			if (tunlink != '')
				uci_set_string(output, `network.${name}.tunlink`, tunlink);
		}

		return;
	}

	let dslite = ubbf_get(config, 'Device.DSLite');
	if (!dslite || !ubbf_to_bool(dslite.Enable))
		return;

	let settings = ubbf_instances(config, 'Device.DSLite.InterfaceSetting');
	let tunlink = wan6_tunlink_resolve();

	generate_dslite(settings, tunlink);
}
uci_comment(output, '# generated by dslite.uc');
render_config();
