// Generated by dm/generate_constraints.py from dm/json_spec/. Do not edit:
// the hand-maintained tables live in the per-domain schema files, and a
// constraints entry there is merged over anything stated here.
//
// Only parameters the shipped model declares and marks writable appear, so
// this is a fraction of what TR-181 states.

'use strict';

export const constraints = {
	"Device.Bridging.Bridge.{i}": {
		"AgingTime": {
			"max": 1000000,
			"min": 10
		},
		"Standard": {
			"enum": [
				"802.1D-2004",
				"802.1Q-2005",
				"802.1Q-2011"
			]
		}
	},
	"Device.Bridging.Bridge.{i}.Port.{i}": {
		"AcceptableFrameTypes": {
			"enum": [
				"AdmitAll",
				"AdmitOnlyVLANTagged",
				"AdmitOnlyPrioUntagged"
			]
		},
		"DefaultUserPriority": {
			"max": 7,
			"min": 0
		},
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"PVID": {
			"max": 4094,
			"min": 1
		},
		"PathCost": {
			"max": 65535,
			"min": 0
		},
		"Priority": {
			"max": 240,
			"min": 0
		},
		"PriorityRegeneration": {
			"list": true,
			"max": 7,
			"min": 0
		},
		"ServiceAccessPriorityTranslation": {
			"list": true,
			"max": 7,
			"min": 0
		},
		"Type": {
			"enum": [
				"ProviderNetworkPort",
				"CustomerNetworkPort",
				"CustomerEdgePort",
				"CustomerVLANPort",
				"VLANUnawarePort"
			]
		}
	},
	"Device.Bridging.Bridge.{i}.STP": {
		"BridgePriority": {
			"max": 61440,
			"min": 0
		},
		"ForwardingDelay": {
			"max": 30,
			"min": 4
		},
		"HelloTime": {
			"max": 1000,
			"min": 100
		},
		"MaxAge": {
			"max": 4000,
			"min": 600
		},
		"Protocol": {
			"enum": [
				"STP",
				"RSTP"
			]
		}
	},
	"Device.Bridging.Bridge.{i}.VLAN.{i}": {
		"Name": {
			"max_length": 64
		},
		"VLANID": {
			"max": 4094,
			"min": 1
		}
	},
	"Device.Bridging.Bridge.{i}.VLANPort.{i}": {
		"Port": {
			"max_length": 256
		},
		"VLAN": {
			"max_length": 256
		}
	},
	"Device.BulkData.Profile.{i}": {
		"ControlFileFormat": {
			"max_length": 128
		},
		"FileTransferPassword": {
			"max_length": 64
		},
		"FileTransferUsername": {
			"max_length": 64
		},
		"Name": {
			"max_length": 255
		},
		"NumberOfRetainedFailedReports": {
			"min": -1
		},
		"ReportingInterval": {
			"min": 1
		},
		"StreamingHost": {
			"max_length": 256
		},
		"StreamingPort": {
			"max": 65535,
			"min": 0
		},
		"StreamingSessionID": {
			"ranges": [
				[
					48,
					57
				],
				[
					65,
					90
				]
			]
		}
	},
	"Device.BulkData.Profile.{i}.CSVEncoding": {
		"ReportFormat": {
			"enum": [
				"ParameterPerRow",
				"ParameterPerColumn"
			]
		},
		"RowTimestamp": {
			"enum": [
				"Unix-Epoch",
				"ISO-8601",
				"None"
			]
		}
	},
	"Device.BulkData.Profile.{i}.HTTP": {
		"Password": {
			"max_length": 256
		},
		"RetryIntervalMultiplier": {
			"max": 65535,
			"min": 1000
		},
		"RetryMinimumWaitInterval": {
			"max": 65535,
			"min": 1
		},
		"Username": {
			"max_length": 256
		}
	},
	"Device.BulkData.Profile.{i}.HTTP.RequestURIParameter.{i}": {
		"Name": {
			"max_length": 64
		},
		"Reference": {
			"max_length": 256
		}
	},
	"Device.BulkData.Profile.{i}.JSONEncoding": {
		"ReportFormat": {
			"enum": [
				"ObjectHierarchy",
				"NameValuePair"
			]
		},
		"ReportTimestamp": {
			"enum": [
				"Unix-Epoch",
				"ISO-8601",
				"None"
			]
		}
	},
	"Device.BulkData.Profile.{i}.MQTT": {
		"PublishQoS": {
			"max": 2,
			"min": 0
		},
		"PublishTopic": {
			"max_length": 65535
		}
	},
	"Device.BulkData.Profile.{i}.Parameter.{i}": {
		"Name": {
			"max_length": 64
		},
		"Reference": {
			"max_length": 256
		}
	},
	"Device.DHCPv4.Client.{i}": {
		"AuthenticationProtocol": {
			"enum": [
				"None",
				"ConfigurationToken",
				"DelayedAuthentication"
			]
		},
		"DSCPMark": {
			"max": 63,
			"min": 0
		},
		"Interface": {
			"max_length": 256
		},
		"PassthroughDHCPPool": {
			"max_length": 256
		}
	},
	"Device.DHCPv4.Client.{i}.ReqOption.{i}": {
		"Tag": {
			"max": 254,
			"min": 1
		}
	},
	"Device.DHCPv4.Client.{i}.SentOption.{i}": {
		"Tag": {
			"max": 254,
			"min": 1
		}
	},
	"Device.DHCPv4.Server.Pool.{i}": {
		"DNSServers": {
			"list": true
		},
		"DomainName": {
			"max_length": 64
		},
		"IPRouters": {
			"list": true
		},
		"Interface": {
			"max_length": 256
		},
		"LeaseTime": {
			"min": -1
		},
		"ReservedAddresses": {
			"list": true
		},
		"VendorClassID": {
			"max_length": 255
		},
		"VendorClassIDMode": {
			"enum": [
				"Exact",
				"Prefix",
				"Suffix",
				"Substring"
			]
		}
	},
	"Device.DHCPv4.Server.Pool.{i}.Option.{i}": {
		"Tag": {
			"max": 254,
			"min": 1
		}
	},
	"Device.DHCPv6.Client.{i}": {
		"AuthenticationProtocol": {
			"enum": [
				"None",
				"ConfigurationToken",
				"DelayedAuthentication",
				"ReconfigureKeyAuthentication"
			]
		},
		"DSCPMark": {
			"max": 63,
			"min": 0
		},
		"Interface": {
			"max_length": 256
		},
		"RequestedOptions": {
			"list": true
		},
		"SuggestedT1": {
			"min": -1
		},
		"SuggestedT2": {
			"min": -1
		}
	},
	"Device.DHCPv6.Client.{i}.SentOption.{i}": {
		"Tag": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.DHCPv6.Server.Pool.{i}": {
		"DSCPMark": {
			"max": 63,
			"min": 0
		},
		"IANAManualPrefixes": {
			"list": true
		},
		"IAPDAddLength": {
			"max": 64
		},
		"IAPDManualPrefixes": {
			"list": true
		},
		"Interface": {
			"max_length": 256
		}
	},
	"Device.DHCPv6.Server.Pool.{i}.Option.{i}": {
		"PassthroughClient": {
			"max_length": 256
		},
		"Tag": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.DNS.Client.Server.{i}": {
		"Interface": {
			"max_length": 256
		}
	},
	"Device.DNS.Relay.Config.{i}": {
		"Forwarders": {
			"list": true,
			"max_length": 256
		},
		"Interface": {
			"max_length": 256
		}
	},
	"Device.DNS.Relay.Forwarding.{i}": {
		"Interface": {
			"max_length": 256
		}
	},
	"Device.DNS.SD": {
		"AdvertisedInterfaces": {
			"list": true
		}
	},
	"Device.DNS.SD.Advertise.{i}": {
		"ApplicationProtocol": {
			"max_length": 15
		},
		"Domain": {
			"max_length": 256
		},
		"InstanceName": {
			"max_length": 63
		},
		"Interface": {
			"max_length": 256
		},
		"Port": {
			"max": 65535
		},
		"TransportProtocol": {
			"enum": [
				"TCP",
				"UDP"
			]
		}
	},
	"Device.DNS.SD.Advertise.{i}.TextRecord.{i}": {
		"Key": {
			"max_length": 255
		},
		"Value": {
			"max_length": 255
		}
	},
	"Device.DNS.Zone.{i}": {
		"Interface": {
			"max_length": 256
		},
		"Name": {
			"max_length": 128
		}
	},
	"Device.DNS.Zone.{i}.Host.{i}": {
		"Host": {
			"max_length": 256
		},
		"Name": {
			"list": true,
			"max_length": 128
		}
	},
	"Device.DSLite.InterfaceSetting.{i}": {
		"EndpointAddressTypePrecedence": {
			"enum": [
				"FQDN",
				"IPv6Address"
			]
		},
		"EndpointAssignmentPrecedence": {
			"enum": [
				"DHCPv6",
				"Static"
			]
		},
		"EndpointName": {
			"max_length": 256
		}
	},
	"Device.DeviceInfo": {
		"FriendlyName": {
			"max_length": 32
		},
		"HostName": {
			"max_length": 255
		},
		"ProvisioningCode": {
			"max_length": 64
		}
	},
	"Device.DeviceInfo.Reboots": {
		"MaxRebootEntries": {
			"min": -1
		}
	},
	"Device.DeviceInfo.TemperatureStatus.TemperatureSensor.{i}": {
		"HighAlarmValue": {
			"min": -274
		},
		"LowAlarmValue": {
			"min": -274
		}
	},
	"Device.DynamicDNS.Client.{i}": {
		"Interface": {
			"max_length": 256
		},
		"Password": {
			"max_length": 256
		},
		"Server": {
			"max_length": 256
		},
		"Username": {
			"max_length": 256
		}
	},
	"Device.DynamicDNS.Client.{i}.Hostname.{i}": {
		"Name": {
			"max_length": 256
		}
	},
	"Device.DynamicDNS.Server.{i}": {
		"Name": {
			"max_length": 64
		},
		"ServerAddress": {
			"max_length": 256
		},
		"ServerPort": {
			"max": 65535,
			"min": 0
		},
		"ServiceName": {
			"max_length": 256
		}
	},
	"Device.Ethernet.Interface.{i}": {
		"AdvertisedLinkModes": {
			"list": true
		},
		"DuplexMode": {
			"enum": [
				"Half",
				"Full",
				"Auto"
			]
		},
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"MDIX": {
			"enum": [
				"Auto",
				"On",
				"Off"
			]
		},
		"MaxBitRate": {
			"min": -1
		}
	},
	"Device.Ethernet.Link.{i}": {
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		}
	},
	"Device.Ethernet.RMONStats.{i}": {
		"VLANID": {
			"max": 4094,
			"min": 0
		}
	},
	"Device.Ethernet.VLANTermination.{i}": {
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"VLANID": {
			"max": 4094,
			"min": 1
		},
		"VLANPriority": {
			"max": 7,
			"min": -1
		}
	},
	"Device.Firewall": {
		"Config": {
			"enum": [
				"High",
				"Low",
				"Off",
				"Advanced",
				"Policy"
			]
		}
	},
	"Device.Firewall.Chain.{i}": {
		"Name": {
			"max_length": 64
		}
	},
	"Device.Firewall.Chain.{i}.Rule.{i}": {
		"ConnectionState": {
			"enum": [
				"INVALID",
				"NEW",
				"RELATED",
				"ESTABLISHED"
			],
			"list": true
		},
		"DSCP": {
			"max": 63,
			"min": -1
		},
		"Description": {
			"max_length": 256
		},
		"DestInterface": {
			"max_length": 256
		},
		"DestPort": {
			"max": 65535,
			"min": -1
		},
		"DestPortRangeMax": {
			"max": 65535,
			"min": -1
		},
		"IPVersion": {
			"ranges": [
				[
					4,
					4
				],
				[
					6,
					6
				],
				[
					-1,
					-1
				]
			]
		},
		"LogRef": {
			"list": true
		},
		"Protocol": {
			"max": 255,
			"min": -1
		},
		"SourceInterface": {
			"max_length": 256
		},
		"SourcePort": {
			"max": 65535,
			"min": -1
		},
		"SourcePortRangeMax": {
			"max": 65535,
			"min": -1
		},
		"Target": {
			"enum": [
				"Drop",
				"Accept",
				"Reject",
				"Return",
				"TargetChain"
			]
		}
	},
	"Device.Firewall.ConnectionTracking.FTP": {
		"Ports": {
			"list": true,
			"max": 65535,
			"min": 0
		}
	},
	"Device.Firewall.ConnectionTracking.IRC": {
		"Ports": {
			"list": true,
			"max": 65535,
			"min": 0
		}
	},
	"Device.Firewall.ConnectionTracking.SIP": {
		"Ports": {
			"list": true,
			"max": 65535,
			"min": 0
		}
	},
	"Device.Firewall.ConnectionTracking.TFTP": {
		"Ports": {
			"list": true,
			"max": 65535,
			"min": 0
		}
	},
	"Device.Firewall.DMZ.{i}": {
		"Description": {
			"max_length": 256
		},
		"Interface": {
			"max_length": 256
		},
		"Origin": {
			"enum": [
				"User",
				"System",
				"Controller"
			]
		}
	},
	"Device.Firewall.InterfaceSetting.{i}": {
		"Interface": {
			"max_length": 256
		}
	},
	"Device.Firewall.Level.{i}": {
		"DefaultPolicy": {
			"enum": [
				"Drop",
				"Accept",
				"Reject"
			]
		},
		"Description": {
			"max_length": 256
		},
		"Name": {
			"max_length": 64
		},
		"Policies": {
			"list": true
		}
	},
	"Device.Firewall.Pinhole.{i}": {
		"Description": {
			"max_length": 256
		},
		"DestPort": {
			"max": 65535,
			"min": -1
		},
		"DestPortRangeMax": {
			"max": 65535,
			"min": -1
		},
		"IPVersion": {
			"ranges": [
				[
					4,
					4
				],
				[
					6,
					6
				],
				[
					-1,
					-1
				]
			]
		},
		"Interface": {
			"max_length": 256
		},
		"LogRef": {
			"list": true
		},
		"Protocol": {
			"list": true,
			"max": 255,
			"min": -1
		},
		"ScheduleRef": {
			"list": true
		},
		"SourcePort": {
			"max": 65535,
			"min": -1
		},
		"SourcePortRangeMax": {
			"max": 65535,
			"min": -1
		},
		"SourcePrefixes": {
			"list": true
		}
	},
	"Device.Firewall.Policy.{i}": {
		"DestinationInterface": {
			"max_length": 256
		},
		"IPVersion": {
			"ranges": [
				[
					4,
					4
				],
				[
					6,
					6
				],
				[
					-1,
					-1
				]
			]
		},
		"LogRef": {
			"list": true
		},
		"ReverseTargetChain": {
			"enum": [
				"Drop",
				"Accept",
				"Reject",
				"Chain"
			]
		},
		"SourceInterface": {
			"max_length": 256
		},
		"TargetChain": {
			"enum": [
				"Drop",
				"Accept",
				"Reject",
				"Chain"
			]
		}
	},
	"Device.Firewall.Service.{i}": {
		"Action": {
			"enum": [
				"Drop",
				"Accept",
				"Reject"
			]
		},
		"DestPort": {
			"list": true,
			"max": 65535,
			"min": -1
		},
		"ICMPType": {
			"max": 255,
			"min": -1
		},
		"IPVersion": {
			"ranges": [
				[
					4,
					4
				],
				[
					6,
					6
				],
				[
					-1,
					-1
				]
			]
		},
		"Interface": {
			"max_length": 256
		},
		"LogRef": {
			"list": true
		},
		"Protocol": {
			"list": true,
			"max": 255,
			"min": -1
		},
		"SourcePrefixes": {
			"list": true
		}
	},
	"Device.Hosts.AccessControl.{i}": {
		"AccessPolicy": {
			"enum": [
				"Allow",
				"Deny"
			]
		},
		"HostName": {
			"max_length": 256
		},
		"PhysAddress": {
			"max_length": 64
		},
		"PhysAddressMask": {
			"max_length": 64
		},
		"ScheduleRef": {
			"list": true
		}
	},
	"Device.Hosts.AccessControl.{i}.Schedule.{i}": {
		"Day": {
			"enum": [
				"Monday",
				"Tuesday",
				"Wednesday",
				"Thursday",
				"Friday",
				"Saturday",
				"Sunday"
			],
			"list": true
		},
		"Duration": {
			"min": 1
		},
		"StartTime": {
			"max_length": 5
		}
	},
	"Device.IEEE1905.AL.ForwardingTable.ForwardingRule.{i}": {
		"InterfaceList": {
			"list": true,
			"max_length": 256
		},
		"PCP": {
			"max": 7,
			"min": 0
		},
		"Vid": {
			"max": 4095,
			"min": 0
		}
	},
	"Device.IEEE1905.AL.Interface.{i}": {
		"PowerState": {
			"enum": [
				"On",
				"Power_Save",
				"Off",
				"Unsupported"
			]
		}
	},
	"Device.IEEE1905.AL.NetworkTopology": {
		"MaxChangeLogEntries": {
			"min": 1
		}
	},
	"Device.IEEE1905.AL.Security": {
		"SetupMethod": {
			"enum": [
				"UCPK",
				"PBC",
				"NFCNK"
			],
			"list": true,
			"list_max_length": 1024
		}
	},
	"Device.IP.Diagnostics.UDPEchoConfig": {
		"Interface": {
			"max_length": 256
		}
	},
	"Device.IP.Interface.{i}": {
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"MaxMTUSize": {
			"max": 65535,
			"min": 64
		}
	},
	"Device.IP.Interface.{i}.IPv6Prefix.{i}": {
		"StaticType": {
			"enum": [
				"Static",
				"Inapplicable",
				"PrefixDelegation",
				"Child"
			]
		}
	},
	"Device.LANConfigSecurity": {
		"ConfigPassword": {
			"max_length": 64
		}
	},
	"Device.NAT.InterfaceSetting.{i}": {
		"Interface": {
			"max_length": 256
		}
	},
	"Device.NAT.PortMapping.{i}": {
		"Description": {
			"max_length": 256
		},
		"ExternalPort": {
			"max": 65535,
			"min": 0
		},
		"ExternalPortEndRange": {
			"max": 65535,
			"min": 0
		},
		"Interface": {
			"max_length": 256
		},
		"InternalClient": {
			"max_length": 256
		},
		"InternalPort": {
			"max": 65535,
			"min": 0
		},
		"Protocol": {
			"enum": [
				"TCP",
				"UDP"
			]
		}
	},
	"Device.NeighborDiscovery.InterfaceSetting.{i}": {
		"RetransTimer": {
			"min": 1
		},
		"RtrSolicitationInterval": {
			"min": 4000
		}
	},
	"Device.Optical.Interface.{i}": {
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"MaxBitRate": {
			"min": -1
		}
	},
	"Device.PCP": {
		"PreferredVersion": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.PCP.Client.{i}.Server.{i}": {
		"PortQuota": {
			"max": 65535
		},
		"ServerNameOrAddress": {
			"max_length": 256
		}
	},
	"Device.PCP.Client.{i}.Server.{i}.InboundMapping.{i}": {
		"Description": {
			"max_length": 256
		},
		"InternalPort": {
			"max": 65535,
			"min": 1
		},
		"ProtocolNumber": {
			"max": 255,
			"min": -1
		},
		"SuggestedExternalPort": {
			"max": 65535,
			"min": 0
		},
		"SuggestedExternalPortEndRange": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.PCP.Client.{i}.Server.{i}.InboundMapping.{i}.Filter.{i}": {
		"PrefixLength": {
			"max": 128,
			"min": 1
		},
		"RemotePort": {
			"max": 65535,
			"min": 0
		},
		"RemotePortEndRange": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.PCP.Client.{i}.Server.{i}.OutboundMapping.{i}": {
		"Description": {
			"max_length": 256
		},
		"InternalPort": {
			"max": 65535,
			"min": 1
		},
		"ProtocolNumber": {
			"max": 255,
			"min": -1
		},
		"RemotePort": {
			"max": 65535,
			"min": 1
		},
		"SuggestedExternalPort": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.PPP.Interface.{i}": {
		"ConnectionTrigger": {
			"enum": [
				"OnDemand",
				"AlwaysOn",
				"Manual"
			]
		},
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"MaxMRUSize": {
			"max": 65535,
			"min": 64
		},
		"Password": {
			"max_length": 64
		},
		"Username": {
			"max_length": 64
		}
	},
	"Device.PPP.Interface.{i}.PPPoE": {
		"ACName": {
			"max_length": 256
		},
		"ServiceName": {
			"max_length": 256
		}
	},
	"Device.QoS.Classification.{i}": {
		"DSCPCheck": {
			"max": 63,
			"min": -1
		},
		"DSCPMark": {
			"min": -2
		},
		"DestPort": {
			"max": 65535,
			"min": -1
		},
		"DestPortRangeMax": {
			"max": 65535,
			"min": -1
		},
		"DestVendorClassID": {
			"max_length": 255
		},
		"EthernetPriorityCheck": {
			"min": -1
		},
		"Ethertype": {
			"min": -1
		},
		"Interface": {
			"max_length": 256
		},
		"Policer": {
			"max_length": 256
		},
		"Protocol": {
			"max": 255,
			"min": -1
		},
		"SourcePort": {
			"max": 65535,
			"min": -1
		},
		"SourcePortRangeMax": {
			"max": 65535,
			"min": -1
		},
		"SourceVendorClassID": {
			"max_length": 255
		},
		"TrafficClass": {
			"min": -1
		},
		"VLANIDCheck": {
			"min": -1
		}
	},
	"Device.QoS.Queue.{i}": {
		"Interface": {
			"max_length": 256
		},
		"Precedence": {
			"min": 1
		},
		"SchedulerAlgorithm": {
			"enum": [
				"WFQ",
				"WRR",
				"SP"
			]
		},
		"ShapingRate": {
			"min": -1
		},
		"TrafficClasses": {
			"list": true,
			"list_max_length": 256
		}
	},
	"Device.QoS.QueueStats.{i}": {
		"Interface": {
			"max_length": 256
		},
		"Queue": {
			"max_length": 256
		}
	},
	"Device.QoS.Shaper.{i}": {
		"Interface": {
			"max_length": 256
		},
		"ShapingRate": {
			"min": -1
		}
	},
	"Device.RouterAdvertisement.InterfaceSetting.{i}": {
		"AdvCurHopLimit": {
			"max": 255
		},
		"AdvDNSSLLifetime": {
			"max": 4294967295
		},
		"AdvDefaultLifetime": {
			"max": 65535
		},
		"AdvPreferredRouterFlag": {
			"enum": [
				"High",
				"Medium",
				"Low"
			]
		},
		"AdvRDNSSLifetime": {
			"max": 4294967295
		},
		"AdvReachableTime": {
			"max": 3600000
		},
		"DNSSL": {
			"list": true
		},
		"MaxRtrAdvInterval": {
			"max": 1800,
			"min": 4
		},
		"MinRtrAdvInterval": {
			"max": 1350,
			"min": 3
		},
		"RDNSS": {
			"list": true
		}
	},
	"Device.RouterAdvertisement.InterfaceSetting.{i}.Option.{i}": {
		"Tag": {
			"max": 65535,
			"min": 0
		}
	},
	"Device.Routing.Router.{i}.IPv4Forwarding.{i}": {
		"ForwardingMetric": {
			"min": -1
		},
		"ForwardingPolicy": {
			"min": -1
		},
		"Interface": {
			"max_length": 256
		}
	},
	"Device.Routing.Router.{i}.IPv6Forwarding.{i}": {
		"ForwardingMetric": {
			"min": -1
		},
		"ForwardingPolicy": {
			"min": -1
		},
		"Interface": {
			"max_length": 256
		}
	},
	"Device.SSH.AuthorizedKey.{i}": {
		"User": {
			"max_length": 256
		}
	},
	"Device.SSH.Server.{i}": {
		"Interface": {
			"max_length": 256
		},
		"Port": {
			"max": 65535,
			"min": 1
		}
	},
	"Device.Security.CABundle.{i}": {
		"CACertificates": {
			"list": true
		}
	},
	"Device.SoftwareModules.ExecEnv.{i}": {
		"InitialExecutionUnitRunLevel": {
			"max": 65535,
			"min": -1
		},
		"InitialRunLevel": {
			"max": 65535
		},
		"Signers": {
			"list": true
		}
	},
	"Device.SoftwareModules.ExecutionUnit.{i}": {
		"RunLevel": {
			"max": 65535
		}
	},
	"Device.Syslog.Action.{i}": {
		"FilterRef": {
			"list": true,
			"max_length": 256
		},
		"SourceRef": {
			"list": true,
			"max_length": 256
		},
		"TemplateRef": {
			"max_length": 256
		}
	},
	"Device.Syslog.Action.{i}.LogRemote": {
		"Port": {
			"max": 65535,
			"min": 1
		},
		"Protocol": {
			"enum": [
				"TCP",
				"UDP",
				"TLS"
			]
		}
	},
	"Device.Syslog.Filter.{i}": {
		"FacilityLevel": {
			"enum": [
				"Kern",
				"User",
				"Mail",
				"Daemon",
				"Auth",
				"Syslog",
				"LPR",
				"News",
				"UUCP",
				"Cron",
				"AuthPriv",
				"FTP",
				"NTP",
				"Audit",
				"Console",
				"Cron2",
				"Local0",
				"Local1",
				"Local2",
				"Local3",
				"Local4",
				"Local5",
				"Local6",
				"Local7",
				"All"
			],
			"list": true
		},
		"Severity": {
			"enum": [
				"Emergency",
				"Alert",
				"Critical",
				"Error",
				"Warning",
				"Notice",
				"Info",
				"Debug",
				"All",
				"None"
			]
		},
		"SeverityCompare": {
			"enum": [
				"Equal",
				"EqualOrHigher"
			]
		},
		"SeverityCompareAction": {
			"enum": [
				"Log",
				"Block",
				"Stop"
			]
		}
	},
	"Device.Syslog.Source.{i}": {
		"FacilityLevel": {
			"enum": [
				"Kern",
				"User",
				"Mail",
				"Daemon",
				"Auth",
				"Syslog",
				"LPR",
				"News",
				"UUCP",
				"Cron",
				"AuthPriv",
				"FTP",
				"NTP",
				"Audit",
				"Console",
				"Cron2",
				"Local0",
				"Local1",
				"Local2",
				"Local3",
				"Local4",
				"Local5",
				"Local6",
				"Local7",
				"All"
			]
		},
		"Severity": {
			"enum": [
				"Emergency",
				"Alert",
				"Critical",
				"Error",
				"Warning",
				"Notice",
				"Info",
				"Debug",
				"All",
				"None"
			]
		}
	},
	"Device.Syslog.Source.{i}.Network": {
		"Interface": {
			"max_length": 256
		},
		"Port": {
			"max": 65535,
			"min": 1
		},
		"Protocol": {
			"enum": [
				"TCP",
				"UDP",
				"TLS"
			]
		}
	},
	"Device.Time": {
		"LocalTimeZone": {
			"max_length": 256
		},
		"NTPServer1": {
			"max_length": 64
		},
		"NTPServer2": {
			"max_length": 64
		},
		"NTPServer3": {
			"max_length": 64
		},
		"NTPServer4": {
			"max_length": 64
		},
		"NTPServer5": {
			"max_length": 64
		}
	},
	"Device.Time.Client.{i}": {
		"Servers": {
			"list": true
		}
	},
	"Device.Time.Server.{i}": {
		"Interface": {
			"max_length": 256
		}
	},
	"Device.USB.Interface.{i}": {
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		}
	},
	"Device.UserInterface.HTTPAccess.{i}": {
		"Interface": {
			"max_length": 256
		},
		"Port": {
			"max": 65535,
			"min": 1
		}
	},
	"Device.Users.Group.{i}": {
		"Groupname": {
			"max_length": 64
		},
		"RoleParticipation": {
			"list": true,
			"list_max_length": 1024
		}
	},
	"Device.Users.Role.{i}": {
		"RequiredCapabilities": {
			"list": true
		},
		"RoleName": {
			"max_length": 64
		}
	},
	"Device.Users.User.{i}": {
		"GroupParticipation": {
			"list": true,
			"list_max_length": 1024
		},
		"Language": {
			"max_length": 16
		},
		"Password": {
			"max_length": 64
		},
		"RoleParticipation": {
			"list": true,
			"list_max_length": 1024
		},
		"Username": {
			"max_length": 64
		}
	},
	"Device.WiFi.AccessPoint.{i}": {
		"AllowedMACAddress": {
			"list": true
		},
		"RetryLimit": {
			"max": 7,
			"min": 0
		},
		"SSIDReference": {
			"max_length": 256
		}
	},
	"Device.WiFi.AccessPoint.{i}.AC.{i}": {
		"AIFSN": {
			"max": 15,
			"min": 2
		},
		"ECWMax": {
			"max": 15,
			"min": 0
		},
		"ECWMin": {
			"max": 15,
			"min": 0
		},
		"OutQLenHistogramIntervals": {
			"list": true
		},
		"TxOpMax": {
			"max": 255,
			"min": 0
		}
	},
	"Device.WiFi.AccessPoint.{i}.Accounting": {
		"InterimInterval": {
			"ranges": [
				[
					0,
					0
				],
				[
					60,
					null
				]
			]
		}
	},
	"Device.WiFi.AccessPoint.{i}.Security": {
		"KeyPassphrase": {
			"max_length": 63,
			"min_length": 8
		},
		"MFPConfig": {
			"enum": [
				"Disabled",
				"Optional",
				"Required"
			]
		}
	},
	"Device.WiFi.AccessPoint.{i}.WPS": {
		"ConfigMethodsEnabled": {
			"list": true
		},
		"PIN": {
			"max_length": 8
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}": {
		"APMetricsReportingInterval": {
			"max": 255
		},
		"AssociatedSTAReportingInterval": {
			"max": 255
		},
		"BTMSteeringDisallowedSTAList": {
			"list": true
		},
		"LocalSteeringDisallowedSTAList": {
			"list": true
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.APMLDConfig.TIDToOpClassPolicy.{i}": {
		"Direction": {
			"enum": [
				"Up",
				"Down"
			]
		},
		"OpClass": {
			"list": true,
			"max": 255
		},
		"TID": {
			"max": 255,
			"min": 0
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Default8021Q.{i}": {
		"DefaultPCP": {
			"max": 7
		},
		"PrimaryVID": {
			"max": 4095
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}": {
		"ChannelUtilizationThreshold": {
			"max": 255
		},
		"RCPISteeringThreshold": {
			"max": 220
		},
		"STAReportingRCPIThreshold": {
			"max": 220
		},
		"SteeringPolicy": {
			"max": 2
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}": {
		"BackhaulAKMsAllowed": {
			"enum": [
				"psk",
				"dpp",
				"sae",
				"psk+sae",
				"dpp+sae",
				"dpp+psk+sae",
				"SuiteSelector"
			],
			"list": true
		},
		"FronthaulAKMsAllowed": {
			"enum": [
				"psk",
				"dpp",
				"sae",
				"psk+sae",
				"dpp+sae",
				"dpp+psk+sae",
				"SuiteSelector"
			],
			"list": true
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.STA.{i}": {
		"CellularDataPreference": {
			"enum": [
				"Excluded",
				"Should not use",
				"Should use"
			]
		},
		"ReAssociationDelay": {
			"max": 65535
		}
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.DisAllowedOpClassChannels.{i}": {
		"ChannelList": {
			"list": true,
			"max": 255
		},
		"OpClass": {
			"max": 255
		}
	},
	"Device.WiFi.DataElements.Network.STABlock.{i}": {
		"BSSID": {
			"list": true
		}
	},
	"Device.WiFi.DataElements.Network.STABlock.{i}.Schedule.{i}": {
		"Day": {
			"enum": [
				"Monday",
				"Tuesday",
				"Wednesday",
				"Thursday",
				"Friday",
				"Saturday",
				"Sunday"
			],
			"list": true
		},
		"Duration": {
			"min": 1
		},
		"StartTime": {
			"max_length": 5
		}
	},
	"Device.WiFi.EndPoint.{i}": {
		"ProfileReference": {
			"max_length": 256
		}
	},
	"Device.WiFi.Radio.{i}": {
		"Channel": {
			"max": 255,
			"min": 1
		},
		"ExtensionChannel": {
			"enum": [
				"AboveControlChannel",
				"BelowControlChannel",
				"Auto"
			]
		},
		"GuardInterval": {
			"enum": [
				"400nsec",
				"800nsec",
				"1xLTF_0.8us",
				"1xLTF_1.6us",
				"2xLTF_0.8us",
				"2xLTF_1.6us",
				"4xLTF_0.8us",
				"4xLTF_3.2us",
				"Auto"
			]
		},
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"OperatingStandards": {
			"list": true
		},
		"PreambleType": {
			"enum": [
				"short",
				"long",
				"auto"
			]
		},
		"RegulatoryDomain": {
			"max_length": 3,
			"min_length": 3
		},
		"RetryLimit": {
			"max": 7,
			"min": 0
		},
		"TransmitPower": {
			"max": 100,
			"min": -1
		}
	},
	"Device.WiFi.SSID.{i}": {
		"LowerLayers": {
			"list": true,
			"list_max_length": 1024
		},
		"SSID": {
			"max_length": 32
		}
	}
};

// Per-table facts. `addable: false` marks a table the CPE maintains itself,
// which a controller may read but not add to; `maxInstances` is the spec's
// maxEntries where it states a finite one.
export const object_meta = {
	"Device": {
		"addable": false
	},
	"Device.Bridging": {
		"addable": false
	},
	"Device.Bridging.Bridge.{i}.Port.{i}.Stats": {
		"addable": false
	},
	"Device.Bridging.Bridge.{i}.STP": {
		"addable": false
	},
	"Device.BulkData": {
		"addable": false
	},
	"Device.BulkData.Profile.{i}.CSVEncoding": {
		"addable": false
	},
	"Device.BulkData.Profile.{i}.HTTP": {
		"addable": false
	},
	"Device.BulkData.Profile.{i}.JSONEncoding": {
		"addable": false
	},
	"Device.BulkData.Profile.{i}.MQTT": {
		"addable": false
	},
	"Device.DHCPv4": {
		"addable": false
	},
	"Device.DHCPv4.Client.{i}.Retransmission": {
		"addable": false
	},
	"Device.DHCPv4.Client.{i}.Stats": {
		"addable": false
	},
	"Device.DHCPv4.Server": {
		"addable": false
	},
	"Device.DHCPv4.Server.Pool.{i}.Client.{i}": {
		"addable": false
	},
	"Device.DHCPv4.Server.Pool.{i}.Client.{i}.IPv4Address.{i}": {
		"addable": false
	},
	"Device.DHCPv4.Server.Pool.{i}.Client.{i}.Option.{i}": {
		"addable": false
	},
	"Device.DHCPv4.Server.Stats": {
		"addable": false
	},
	"Device.DHCPv6": {
		"addable": false
	},
	"Device.DHCPv6.Client.{i}.ReceivedOption.{i}": {
		"addable": false
	},
	"Device.DHCPv6.Client.{i}.Retransmission": {
		"addable": false
	},
	"Device.DHCPv6.Client.{i}.Server.{i}": {
		"addable": false
	},
	"Device.DHCPv6.Client.{i}.Stats": {
		"addable": false
	},
	"Device.DHCPv6.Server": {
		"addable": false
	},
	"Device.DHCPv6.Server.Pool.{i}.Client.{i}": {
		"addable": false
	},
	"Device.DHCPv6.Server.Pool.{i}.Client.{i}.IPv6Address.{i}": {
		"addable": false
	},
	"Device.DHCPv6.Server.Pool.{i}.Client.{i}.IPv6Prefix.{i}": {
		"addable": false
	},
	"Device.DHCPv6.Server.Stats": {
		"addable": false
	},
	"Device.DNS": {
		"addable": false
	},
	"Device.DNS.Client": {
		"addable": false
	},
	"Device.DNS.Diagnostics": {
		"addable": false
	},
	"Device.DNS.Relay": {
		"addable": false
	},
	"Device.DNS.SD": {
		"addable": false
	},
	"Device.DNS.SD.Service.{i}": {
		"addable": false
	},
	"Device.DNS.SD.Service.{i}.TextRecord.{i}": {
		"addable": false
	},
	"Device.DSLite": {
		"addable": false
	},
	"Device.DSLite.InterfaceSetting.{i}": {
		"addable": false
	},
	"Device.DeviceInfo": {
		"addable": false
	},
	"Device.DeviceInfo.FirmwareImage.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.KernelFaults": {
		"addable": false
	},
	"Device.DeviceInfo.KernelFaults.KernelFault.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.MemoryStatus": {
		"addable": false
	},
	"Device.DeviceInfo.NetworkProperties": {
		"addable": false
	},
	"Device.DeviceInfo.ProcessFaults": {
		"addable": false
	},
	"Device.DeviceInfo.ProcessFaults.ProcessFault.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.ProcessStatus": {
		"addable": false
	},
	"Device.DeviceInfo.ProcessStatus.CPU.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.ProcessStatus.Process.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.Processor.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.Reboots": {
		"addable": false
	},
	"Device.DeviceInfo.Reboots.Reboot.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.TemperatureStatus": {
		"addable": false
	},
	"Device.DeviceInfo.TemperatureStatus.TemperatureSensor.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.VendorConfigFile.{i}": {
		"addable": false
	},
	"Device.DeviceInfo.VendorLogFile.{i}": {
		"addable": false
	},
	"Device.DynamicDNS": {
		"addable": false
	},
	"Device.Ethernet": {
		"addable": false
	},
	"Device.Ethernet.Interface.{i}": {
		"addable": false
	},
	"Device.Ethernet.Interface.{i}.Stats": {
		"addable": false
	},
	"Device.Ethernet.Link.{i}.Stats": {
		"addable": false
	},
	"Device.Ethernet.VLANTermination.{i}.Stats": {
		"addable": false
	},
	"Device.Ethernet.WoL": {
		"addable": false
	},
	"Device.Firewall": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking.FTP": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking.H323": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking.IRC": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking.PPTP": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking.SIP": {
		"addable": false
	},
	"Device.Firewall.ConnectionTracking.TFTP": {
		"addable": false
	},
	"Device.GatewayInfo": {
		"addable": false
	},
	"Device.Hosts": {
		"addable": false
	},
	"Device.Hosts.Host.{i}": {
		"addable": false
	},
	"Device.Hosts.Host.{i}.IPv4Address.{i}": {
		"addable": false
	},
	"Device.Hosts.Host.{i}.IPv6Address.{i}": {
		"addable": false
	},
	"Device.Hosts.Host.{i}.WANStats": {
		"addable": false
	},
	"Device.IEEE1905": {
		"addable": false
	},
	"Device.IEEE1905.AL": {
		"addable": false
	},
	"Device.IEEE1905.AL.ForwardingTable": {
		"addable": false
	},
	"Device.IEEE1905.AL.Interface.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.Interface.{i}.Link.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.Interface.{i}.Link.{i}.Metric": {
		"addable": false
	},
	"Device.IEEE1905.AL.Interface.{i}.VendorProperties.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.ChangeLog.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.BridgingTuple.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.IEEE1905Neighbor.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.IEEE1905Neighbor.{i}.Metric.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.IPv4Address.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.IPv6Address.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.Interface.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.L2Neighbor.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.NonIEEE1905Neighbor.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkTopology.IEEE1905Device.{i}.VendorProperties.{i}": {
		"addable": false
	},
	"Device.IEEE1905.AL.NetworkingRegistrar": {
		"addable": false
	},
	"Device.IEEE1905.AL.Security": {
		"addable": false
	},
	"Device.IP": {
		"addable": false
	},
	"Device.IP.Diagnostics": {
		"addable": false
	},
	"Device.IP.Diagnostics.UDPEchoConfig": {
		"addable": false
	},
	"Device.IP.Interface.{i}.Stats": {
		"addable": false
	},
	"Device.InterfaceStack.{i}": {
		"addable": false
	},
	"Device.LANConfigSecurity": {
		"addable": false
	},
	"Device.LEDs": {
		"addable": false
	},
	"Device.LEDs.LED.{i}": {
		"addable": false
	},
	"Device.LLDP": {
		"addable": false
	},
	"Device.LLDP.Discovery.Device.{i}": {
		"addable": false
	},
	"Device.LLDP.Discovery.Device.{i}.DeviceInformation": {
		"addable": false
	},
	"Device.LLDP.Discovery.Device.{i}.DeviceInformation.VendorSpecific.{i}": {
		"addable": false
	},
	"Device.LLDP.Discovery.Device.{i}.Port.{i}": {
		"addable": false
	},
	"Device.LLDP.Discovery.Device.{i}.Port.{i}.LinkInformation": {
		"addable": false
	},
	"Device.LocalAgent": {
		"addable": false
	},
	"Device.NAT": {
		"addable": false
	},
	"Device.NeighborDiscovery": {
		"addable": false
	},
	"Device.Optical": {
		"addable": false
	},
	"Device.Optical.Interface.{i}": {
		"addable": false
	},
	"Device.Optical.Interface.{i}.Stats": {
		"addable": false
	},
	"Device.PCP": {
		"addable": false
	},
	"Device.PCP.Client.{i}.PCPProxy": {
		"addable": false
	},
	"Device.PCP.Client.{i}.UPnPIWF": {
		"addable": false
	},
	"Device.PPP": {
		"addable": false
	},
	"Device.PPP.Interface.{i}.IPCP": {
		"addable": false
	},
	"Device.PPP.Interface.{i}.IPv6CP": {
		"addable": false
	},
	"Device.PPP.Interface.{i}.PPPoE": {
		"addable": false
	},
	"Device.PPP.Interface.{i}.Stats": {
		"addable": false
	},
	"Device.QoS": {
		"addable": false
	},
	"Device.RouterAdvertisement": {
		"addable": false
	},
	"Device.Routing": {
		"addable": false
	},
	"Device.Routing.RouteInformation": {
		"addable": false
	},
	"Device.Routing.RouteInformation.InterfaceSetting.{i}": {
		"addable": false
	},
	"Device.SFPs": {
		"addable": false
	},
	"Device.SFPs.Mgmt": {
		"addable": false
	},
	"Device.SFPs.Mgmt.SFF8472.{i}": {
		"addable": false
	},
	"Device.SFPs.Mgmt.SFF8472.{i}.Transceiver": {
		"addable": false
	},
	"Device.SFPs.Mgmt.SFF8472.{i}.Transceiver.Alarms": {
		"addable": false
	},
	"Device.SFPs.Mgmt.SFF8472.{i}.Transceiver.Status": {
		"addable": false
	},
	"Device.SFPs.Mgmt.SFF8472.{i}.Transceiver.Thresholds": {
		"addable": false
	},
	"Device.SFPs.Mgmt.SFF8472.{i}.Transceiver.Warnings": {
		"addable": false
	},
	"Device.SFPs.SFPCage.{i}": {
		"addable": false
	},
	"Device.SSH": {
		"addable": false
	},
	"Device.Security": {
		"addable": false
	},
	"Device.Security.CABundle.{i}": {
		"addable": false
	},
	"Device.Security.Certificate.{i}": {
		"addable": false
	},
	"Device.SoftwareModules": {
		"addable": false
	},
	"Device.SoftwareModules.DeploymentUnit.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecEnv.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecEnv.{i}.ApplicationData.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecEnvClass.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecEnvClass.{i}.Capability.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecutionUnit.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecutionUnit.{i}.AutoRestart": {
		"addable": false
	},
	"Device.SoftwareModules.ExecutionUnit.{i}.EnvVariable.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecutionUnit.{i}.HostObject.{i}": {
		"addable": false
	},
	"Device.SoftwareModules.ExecutionUnit.{i}.NetworkConfig": {
		"addable": false
	},
	"Device.Syslog": {
		"addable": false
	},
	"Device.Syslog.Action.{i}.LogFile": {
		"addable": false
	},
	"Device.Syslog.Action.{i}.LogRemote": {
		"addable": false
	},
	"Device.Syslog.Source.{i}.Network": {
		"addable": false
	},
	"Device.Time": {
		"addable": false
	},
	"Device.USB": {
		"addable": false
	},
	"Device.USB.Interface.{i}": {
		"addable": false
	},
	"Device.USB.Interface.{i}.Stats": {
		"addable": false
	},
	"Device.USB.Port.{i}": {
		"addable": false
	},
	"Device.USB.USBHosts": {
		"addable": false
	},
	"Device.USB.USBHosts.Host.{i}.Device.{i}": {
		"addable": false
	},
	"Device.USB.USBHosts.Host.{i}.Device.{i}.Configuration.{i}": {
		"addable": false
	},
	"Device.USB.USBHosts.Host.{i}.Device.{i}.Configuration.{i}.Interface.{i}": {
		"addable": false
	},
	"Device.UserInterface": {
		"addable": false
	},
	"Device.UserInterface.HTTPAccess.{i}.Session.{i}": {
		"addable": false
	},
	"Device.Users": {
		"addable": false
	},
	"Device.WiFi": {
		"addable": false
	},
	"Device.WiFi.AccessPoint.{i}.AC.{i}": {
		"addable": false,
		"maxInstances": 4
	},
	"Device.WiFi.AccessPoint.{i}.Accounting": {
		"addable": false
	},
	"Device.WiFi.AccessPoint.{i}.AssociatedDevice.{i}": {
		"addable": false
	},
	"Device.WiFi.AccessPoint.{i}.Security": {
		"addable": false
	},
	"Device.WiFi.AccessPoint.{i}.WPS": {
		"addable": false
	},
	"Device.WiFi.DataElements": {
		"addable": false
	},
	"Device.WiFi.DataElements.AssociationEvent": {
		"addable": false
	},
	"Device.WiFi.DataElements.AssociationEvent.AssociationEventData.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.AssociationEvent.AssociationEventData.{i}.WiFi6Capabilities": {
		"addable": false
	},
	"Device.WiFi.DataElements.DisassociationEvent": {
		"addable": false
	},
	"Device.WiFi.DataElements.DisassociationEvent.DisassociationEventData.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.FailedConnectionEvent": {
		"addable": false
	},
	"Device.WiFi.DataElements.FailedConnectionEvent.FailedConnectionEventData.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.APMLDConfig": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.AffiliatedAP.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.LinkToOpClassMap.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.STAMLD.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.STAMLD.{i}.AffiliatedSTA.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.STAMLD.{i}.STAMLDConfig": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.STAMLD.{i}.STATIDLinkMap.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.STAMLD.{i}.WiFi7Capabilities": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.APMLD.{i}.TIDLinkMap.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.AnticipatedChannelUsage.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.AnticipatedChannelUsage.{i}.Entry.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.AnticipatedChannels.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.BackhaulDown.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.CACStatus.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.CACStatus.{i}.CACActiveChannel.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.CACStatus.{i}.CACAvailableChannel.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.CACStatus.{i}.CACNonOccupancyChannel.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.IEEE1905Security.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.MultiAPDevice": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.MultiAPDevice.Backhaul": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.MultiAPDevice.Backhaul.CurrentOperatingClassProfile.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.MultiAPDevice.Backhaul.Stats": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.MultiAPSteering": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.QMDescriptor.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.STA.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.STA.{i}.MultiAPSTA": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.STA.{i}.MultiAPSTA.SteeringHistory.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.STA.{i}.MultiAPSTA.SteeringSummaryStats": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BSS.{i}.STA.{i}.WiFi6Capabilities": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.BackhaulSta": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.CACCapability": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.CACCapability.CACMethod.{i}": {
		"addable": false,
		"maxInstances": 4
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.CACCapability.CACMethod.{i}.OpClassChannels.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.AKMBackhaul.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.AKMFrontHaul.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.CapableOperatingClassProfile.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi6APRole": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi6bSTARole": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7APRole": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7APRole.EMLMRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7APRole.EMLSRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7APRole.NSTRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7APRole.STRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7bSTARole": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7bSTARole.EMLMRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7bSTARole.EMLSRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7bSTARole.NSTRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.Capabilities.WiFi7bSTARole.STRFreqSeparation.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.CurrentOperatingClassProfile.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.MultiAPRadio": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.OpClassPreference.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.ScanCapability": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.ScanCapability.OpClassChannels.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.ScanResult.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.ScanResult.{i}.OpClassScan.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.ScanResult.{i}.OpClassScan.{i}.ChannelScan.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.ScanResult.{i}.OpClassScan.{i}.ChannelScan.{i}.NeighborBSS.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.SpatialReuse": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.Radio.{i}.UnassociatedSTA.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.SPRule.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.SSIDtoVIDMapping.{i}": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.bSTAMLD": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.Device.{i}.bSTAMLD.bSTAMLDConfig": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.MultiAPSteeringSummaryStats": {
		"addable": false
	},
	"Device.WiFi.DataElements.Network.SSID.{i}": {
		"addable": false
	},
	"Device.WiFi.Radio.{i}": {
		"addable": false
	},
	"Device.WiFi.Radio.{i}.Stats": {
		"addable": false
	},
	"Device.WiFi.SSID.{i}.Stats": {
		"addable": false
	}
};
