#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
PROG=/usr/libexec/ubbf/udpecho-server

start_service() {
	local enabled port source_ip echo_plus

	config_load ubbf
	config_get_bool enabled udpecho enabled 0
	[ "$enabled" -eq 0 ] && return

	config_get port udpecho port 7
	config_get source_ip udpecho source_ip ""
	config_get_bool echo_plus udpecho echo_plus 0

	procd_open_instance
	procd_set_param command "$PROG" -p "$port"

	[ -n "$source_ip" ] && procd_append_param command -s "$source_ip"
	[ "$echo_plus" -eq 1 ] && procd_append_param command -e

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "ubbf"
}
