function render_config() {
	/**
	 * Populates device render state with Optical interface admin enable.
	 *
	 * Mirrors the Ethernet pattern: writes `enabled` into render_state.device,
	 * which device.uc later emits as `network.@device[<name>].enabled`. Only
	 * rows that already carry a Name (i.e. were touched by a set) participate;
	 * untouched cages leave the existing UCI device state alone.
	 *
	 * @param {array} instances - Optical.Interface instances from stored config
	 */
	function populate_interface_settings(instances) {
		for (let iface in instances) {
			let name = iface.Name;
			if (!name)
				continue;

			let enabled = ubbf_to_bool(iface.Enable);
			device_state_set(render_state, name, 'enabled', enabled ? '1' : '0');
		}
	}

	let interfaces = ubbf_instances(config, 'Device.Optical.Interface');
	if (length(interfaces)) {
		populate_interface_settings(interfaces);
		services.set_enabled('network', true);
	}
}
uci_comment(output, '# generated by usfpd/render.uc');
render_config();
