#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/uwsd
CONF=/tmp/uwsd-ubbf-testbed.conf
PORT=7548

start_service() {
	# apply-config answers only once the network has settled, which takes
	# longer than the 10 s uwsd allows a script backend by default.
	cat > "$CONF" <<EOF
backend testbed {
	run-script /usr/share/ucode/ubbf/testbed/uwsd-handler.uc;
}

listen :$PORT {
	match-path /rpc {
		use-backend testbed;
	}

	idle-timeout 600000;
	transfer-timeout 120000;
}
EOF

	procd_open_instance
	procd_set_param command "$PROG" --conf "$CONF"
	procd_set_param file "$CONF"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
