function render_config() {
	/**
	 * Emits /etc/config/admz from Device.NAT.X_UBBF_IPPassthrough so
	 * the admzd daemon picks up configuration changes on every
	 * ubbf-apply. The daemon (via procd's reload trigger on the
	 * 'admz' config) reloads the UCI and reconciles the kernel state
	 * machine.
	 *
	 * UCI shape:
	 *   config admz 'main'
	 *       option enable '1|0'
	 *       option advanced_dmz_host '<lowercase-mac>'
	 *       option lease_time '<seconds>'           (clamped [60, 604800])
	 *       option wan_iface  '<netifd-name>'       (e.g. 'wan')
	 *       option lan_dev    '<l2-device>'         (e.g. 'br-lan')
	 *       option secondary_ip '198.18.0.1'
	 *       list   management_port '<tcp-port>'     (one per WAN-bound svc)
	 */
	function render_admz() {
		let admz = ubbf_get(config, 'Device.NAT.X_UBBF_IPPassthrough');

		if (!admz) {
			services.set_enabled('admz', false);
			return;
		}

		let enable = ubbf_to_bool(admz.Enable);
		let mac = replace(lc(admz.AdvancedDMZhost ?? ''), '-', ':', true);

		let lease_time = ubbf_to_int(admz.LeaseTime) ?? 3600;
		if (lease_time < 60)
			lease_time = 60;
		if (lease_time > 604800)
			lease_time = 604800;

		// First upstream IP.Interface for the netifd ubus call; first
		// non-upstream IP.Interface's L2 device for kernel-side ops
		// (proxy-arp, /32 route, neigh entries).
		let wan_iface_name = null;
		let lan_dev = null;
		for (let iface in ubbf_instances(config, 'Device.IP.Interface')) {
			if (!iface.Name)
				continue;
			if (ubbf_to_bool(iface.Upstream)) {
				if (!wan_iface_name)
					wan_iface_name = iface.Name;
				continue;
			}
			if (!lan_dev) {
				let dev = lower_layer_resolve_vlan(config, iface.LowerLayers);
				if (dev)
					lan_dev = dev;
			}
		}

		// Management-port carve-out list. Scan TR-181 for WAN-bound SSH
		// and HTTPS services; the daemon does not act on this directly
		// (the firewall-admz.uc render emits the DNAT redirects) but
		// the list is published via ubus admz status for observability.
		let mgmt_ports = [];
		for (let s in ubbf_instances(config, 'Device.SSH.Server')) {
			if (!ubbf_to_bool(s.Enable))
				continue;
			if (!s.Interface || s.Interface == '')
				continue;
			let iface = ubbf_get(config, s.Interface);
			if (!ubbf_to_bool(iface?.Upstream))
				continue;
			let port = ubbf_to_int(s.Port) ?? 22;
			push(mgmt_ports, port);
		}
		for (let h in ubbf_instances(config, 'Device.UserInterface.HTTPAccess')) {
			if (!ubbf_to_bool(h.Enable))
				continue;
			if (!h.Interface || h.Interface == '')
				continue;
			let iface = ubbf_get(config, h.Interface);
			if (!ubbf_to_bool(iface?.Upstream))
				continue;
			let port = ubbf_to_int(h.Port) ?? 443;
			push(mgmt_ports, port);
		}

		// admzd always runs when the section exists: when ADMZ is
		// disabled the daemon idles in DISABLED state and the proto
		// handler (admz.script) behaves like dhcp.script.
		services.set_enabled('admz', !!wan_iface_name);

		uci_named_section(output, 'admz.main', 'admz');
		uci_set_boolean(output, 'admz.main.enable', enable);
		uci_set_string(output, 'admz.main.advanced_dmz_host', mac);
		uci_set_number(output, 'admz.main.lease_time', lease_time);
		if (wan_iface_name)
			uci_set_string(output, 'admz.main.wan_iface', wan_iface_name);
		if (lan_dev)
			uci_set_string(output, 'admz.main.lan_dev', lan_dev);
		uci_set_string(output, 'admz.main.secondary_ip', '198.18.0.1');
		for (let p in mgmt_ports)
			uci_list_string(output, 'admz.main.management_port', sprintf('%d', p));

		// Override network.<wan>.proto to 'admz' so udhcpc runs under
		// /lib/netifd/proto/admz.sh + /lib/netifd/admz.script. The
		// script reads admz.main.enable on every bound/renew so the
		// Enable toggle does not require ifdown/ifup -- the renderer
		// rewrites UCI, admzd's reload hook fires a renew, the script
		// re-evaluates and applies the right address (198.18.0.1 vs the
		// leased IP). When admz.main.enable=0 the script is
		// byte-equivalent to dhcp.script, so leaving proto=admz on at
		// all times is safe.
		if (wan_iface_name)
			uci_set_string(output, sprintf('network.%s.proto', wan_iface_name), 'admz');
	}

	render_admz();
}
uci_comment(output, '# generated by admz.uc');
render_config();
