function render_config() {

	/**
	 * Reads container definitions from UCI containers config and groups
	 * port_forward sections under their parent container.
	 *
	 * @returns {array} Array of container objects with name, share_parent_network and port_forwards
	 */
	function uci_containers_read() {
		let uci = uci_cursor();
		if (!uci.load('containers'))
			return [];

		let all = uci.get_all('containers');
		if (!all)
			return [];

		let containers = {};
		for (let sid, section in all) {
			if (section['.type'] != 'container')
				continue;
			containers[sid] = {
				name: sid,
				share_parent_network: section.share_parent_network == '1',
				port_forwards: []
			};
		}

		for (let sid, section in all) {
			if (section['.type'] != 'container_port_forward')
				continue;
			let ct = containers[section.container];
			if (!ct)
				continue;
			push(ct.port_forwards, {
				external_port: section.external_port ?? '',
				internal_port: section.internal_port ?? section.external_port ?? '',
				protocol: section.protocol ?? 'tcp'
			});
		}

		return values(containers);
	}

	let configs = uci_containers_read();
	let networked = [];

	for (let cfg in configs) {
		if (cfg.share_parent_network)
			continue;
		push(networked, cfg);
	}

	if (length(configs))
		services.set_enabled('uxc', true);

	if (!length(networked))
		return;


	uci_comment(output, 'container bridge infrastructure');

	device_state_set(render_state, 'br-virt', 'name', 'br-virt');
	device_state_set(render_state, 'br-virt', 'type', 'bridge');

	uci_named_section(output, 'network.virt', 'interface');
	uci_set_string(output, 'network.virt.device', 'br-virt');
	uci_set_string(output, 'network.virt.proto', 'static');
	uci_set_string(output, 'network.virt.ipaddr', '10.0.0.1');
	uci_set_string(output, 'network.virt.netmask', '255.255.255.0');

	uci_named_section(output, 'dhcp.virt', 'dhcp');
	uci_set_string(output, 'dhcp.virt.interface', 'virt');
	uci_set_number(output, 'dhcp.virt.start', 8);
	uci_set_number(output, 'dhcp.virt.limit', 240);
	uci_set_string(output, 'dhcp.virt.leasetime', '12h');
	uci_set_string(output, 'dhcp.virt.domain', 'virt');
	uci_set_string(output, 'dhcp.virt.dhcpv4', 'server');

	uci_named_section(output, 'firewall.virt_zone', 'zone');
	uci_set_string(output, 'firewall.virt_zone.name', 'virt');
	uci_set_string(output, 'firewall.virt_zone.network', 'virt');
	uci_set_string(output, 'firewall.virt_zone.input', 'ACCEPT');
	uci_set_string(output, 'firewall.virt_zone.output', 'ACCEPT');
	uci_set_string(output, 'firewall.virt_zone.forward', 'ACCEPT');

	uci_named_section(output, 'firewall.virt_fwd_wan', 'forwarding');
	uci_set_string(output, 'firewall.virt_fwd_wan.src', 'virt');
	uci_set_string(output, 'firewall.virt_fwd_wan.dest', 'wan');

	uci_named_section(output, 'firewall.virt_fwd_lan', 'forwarding');
	uci_set_string(output, 'firewall.virt_fwd_lan.src', 'lan');
	uci_set_string(output, 'firewall.virt_fwd_lan.dest', 'virt');

	for (let cfg in networked) {
		let name = cfg.name;
		let host_dev = sprintf('h-%s', name);
		let peer_dev = sprintf('v-%s', name);
		let dev_key = sprintf('veth_%s', name);
		let iface_key = sprintf('virt_%s', name);

		uci_comment(output, sprintf('container: %s', name));

		device_state_set(render_state, dev_key, 'name', host_dev);
		device_state_set(render_state, dev_key, 'type', 'veth');
		device_state_set(render_state, dev_key, 'peer_name', peer_dev);

		device_state_list_add(render_state, 'br-virt', 'ports', host_dev);

		uci_named_section(output, sprintf('network.%s', iface_key), 'interface');
		uci_set_string(output, sprintf('network.%s.device', iface_key), peer_dev);
		uci_set_string(output, sprintf('network.%s.proto', iface_key), 'dhcp');
		uci_set_string(output, sprintf('network.%s.jail', iface_key), name);
		uci_set_string(output, sprintf('network.%s.jail_device', iface_key), 'eth0');

		for (let i = 0; i < length(cfg.port_forwards); i++) {
			let pf = cfg.port_forwards[i];
			let rule_name = sprintf('%s_p%d', name, i);

			uci_named_section(output, sprintf('firewall.%s', rule_name), 'redirect');
			uci_set_string(output, sprintf('firewall.%s.name', rule_name),
				sprintf('%s port %s', name, pf.external_port));
			uci_set_string(output, sprintf('firewall.%s.src', rule_name), 'lan');
			uci_set_string(output, sprintf('firewall.%s.src_dport', rule_name), pf.external_port);
			uci_set_string(output, sprintf('firewall.%s.dest', rule_name), 'virt');
			uci_set_string(output, sprintf('firewall.%s.dest_port', rule_name),
				pf.internal_port ?? pf.external_port);
			uci_set_string(output, sprintf('firewall.%s.proto', rule_name), pf.protocol ?? 'tcp');
			uci_set_string(output, sprintf('firewall.%s.target', rule_name), 'DNAT');
		}
	}

}
uci_comment(output, '# generated by containers.uc');
render_config();
