function render_config() {
	/**
	 * Generates UCI ddns service sections from DynamicDNS Client+Hostname pairs.
	 *
	 * Each Client/Hostname combination produces one UCI 'config service' section
	 * in /etc/config/ddns. The Client provides credentials, interface, and server
	 * reference; the Hostname provides the domain name to update.
	 *
	 * @returns {string} UCI batch output for ddns configuration
	 */
	function generate_ddns() {
		let any_enabled = false;

		let clients = ubbf_instances(config, 'Device.DynamicDNS.Client');

		for (let client in clients) {
			if (!ubbf_to_bool(client.Enable))
				continue;

			let server_ref = client.Server;
			let server = server_ref ? ubbf_get(config, server_ref) : null;
			if (!server)
				continue;

			let hostnames = ubbf_instances(config, client['.path'] + '.Hostname');

			for (let hostname in hostnames) {
				if (!ubbf_to_bool(hostname.Enable))
					continue;

				let name = hostname.Name;
				if (!name || name == '')
					continue;

				let section_name = ubbf.name_sanitise(sprintf('ddns_%s_%s',
					client['.instance'], hostname['.instance']));

				any_enabled = true;

				uci_comment(output, sprintf('## DDNS %s', name));
				uci_named_section(output, `ddns.${section_name}`, 'service');
				uci_set_boolean(output, `ddns.${section_name}.enabled`, true);

				if (server.ServiceName && server.ServiceName != '')
					uci_set_string(output, `ddns.${section_name}.service_name`, server.ServiceName);

				if (server.ServiceName == 'custom' && server.ServerAddress && server.ServerAddress != '')
					uci_set_string(output, `ddns.${section_name}.update_url`, server.ServerAddress);

				let use_https = (server.Protocol == 'HTTPS');
				uci_set_boolean(output, `ddns.${section_name}.use_https`, use_https);

				uci_set_string(output, `ddns.${section_name}.domain`, name);
				uci_set_string(output, `ddns.${section_name}.lookup_host`, name);

				if (client.Username && client.Username != '')
					uci_set_string(output, `ddns.${section_name}.username`, client.Username);

				if (client.Password && client.Password != '')
					uci_set_string(output, `ddns.${section_name}.password`, client.Password);

				let iface_name = client.Interface ? interface_to_name(config, client.Interface) : null;
				if (iface_name) {
					uci_set_string(output, `ddns.${section_name}.bind_network`, iface_name);
					uci_set_string(output, `ddns.${section_name}.ip_source`, 'interface');
					uci_set_string(output, `ddns.${section_name}.ip_interface`, iface_name);
				}

				let check_interval = ubbf_to_int(server.CheckInterval);
				if (check_interval && check_interval > 0) {
					uci_set_number(output, `ddns.${section_name}.check_interval`, int(check_interval / 60) || 1);
					uci_set_string(output, `ddns.${section_name}.check_unit`, 'minutes');
				}

				let retry_interval = ubbf_to_int(server.RetryInterval);
				if (retry_interval && retry_interval > 0) {
					uci_set_number(output, `ddns.${section_name}.retry_interval`, retry_interval);
					uci_set_string(output, `ddns.${section_name}.retry_unit`, 'seconds');
				}

				let max_retries = ubbf_to_int(server.MaxRetries);
				if (max_retries && max_retries > 0)
					uci_set_number(output, `ddns.${section_name}.retry_max_count`, max_retries);
			}
		}

		services.set_enabled('ddns', any_enabled);
		return;
	}

	let ddns = ubbf_get(config, 'Device.DynamicDNS');
	if (!ddns)
		return;

	generate_ddns();
}
uci_comment(output, '# generated by ddns.uc');
render_config();
