function render_config() {
	let deviceinfo = ubbf_get(config, 'Device.DeviceInfo');
	if (!deviceinfo)
		return;

	let device_runtime = deviceinfo_get();

	/**
	 * Generates UCI system configuration from device info.
	 *
	 * @param {object} di - DeviceInfo data model object
	 * @returns {string} UCI batch output for system settings
	 */
	function generate_deviceinfo(di) {

		uci_named_section(output, 'system.@system[0]', 'system');

		let hostname = di.HostName;
		if (hostname && hostname != '')
			uci_set_string(output, 'system.@system[0].hostname', hostname);

		let friendly_name = di.FriendlyName;
		if (friendly_name && friendly_name != '')
			uci_set_string(output, 'system.@system[0].friendly_name', friendly_name);

		let serial_number = di.SerialNumber;
		if (!serial_number || serial_number == '')
			serial_number = device_runtime.SerialNumber;
		if (serial_number && serial_number != '')
			uci_set_string(output, 'system.@system[0].serial_number', serial_number);

		return;
	}

	/**
	 * Writes the writable-limit fields into the meta section of a fault file.
	 * Backend (`ubbf-device`) consumes these without parsing config.json.
	 * No-op when the stored limits already match, preserving counter fields.
	 *
	 * @param {string} path - Absolute path to the fault JSON file
	 * @param {number} max_entries - Desired MaxKernelFaultEntries / MaxProcessFaultEntries
	 * @param {boolean} rotate - Desired RotateKernelFaultEntries / RotateProcessFaultEntries
	 * @param {number} min_free - Desired MinFreeSpace in KiB
	 */
	function fault_limits_sync(path, max_entries, rotate, min_free) {
		let state = { meta: {}, faults: [] };
		let data = fs.readfile(path);
		if (data) {
			let parsed = json(data);
			if (type(parsed) == 'array')
				state = { meta: {}, faults: parsed };
			else if (type(parsed) == 'object')
				state = { meta: parsed.meta ?? {}, faults: parsed.faults ?? [] };
		}

		if (state.meta.max_entries == max_entries &&
		    state.meta.rotate == rotate &&
		    state.meta.min_free_space == min_free)
			return;

		state.meta.max_entries = max_entries;
		state.meta.rotate = rotate;
		state.meta.min_free_space = min_free;

		fs.writefile(path, sprintf('%.J\n', state));
	}

	let kf = ubbf_get(config, 'Device.DeviceInfo.KernelFaults');
	if (kf)
		fault_limits_sync('/etc/ubbf/kernel-faults.json',
			ubbf_to_int(kf.MaxKernelFaultEntries ?? '100'),
			ubbf_to_bool(kf.RotateKernelFaultEntries ?? 'true'),
			ubbf_to_int(kf.MinFreeSpace ?? '0'));

	let pf = ubbf_get(config, 'Device.DeviceInfo.ProcessFaults');
	if (pf)
		fault_limits_sync('/etc/ubbf/process-faults.json',
			ubbf_to_int(pf.MaxProcessFaultEntries ?? '100'),
			ubbf_to_bool(pf.RotateProcessFaultEntries ?? 'true'),
			ubbf_to_int(pf.MinFreeSpace ?? '0'));

	generate_deviceinfo(deviceinfo);
}
uci_comment(output, '# generated by deviceinfo.uc');
render_config();
