function render_config() {
	/**
	 * Generates UCI network device sections from render state.
	 *
	 * @returns {string} UCI batch output for all devices
	 */
	function generate_devices() {

		for (let name, dev in render_state.device) {
			if (!dev?.name)
				continue;

			uci_section(output, 'network device');
			uci_set_string(output, 'network.@device[-1].name', dev.name);

			if (dev.type)
				uci_set_string(output, 'network.@device[-1].type', dev.type);
			if (dev.mtu)
				uci_set_string(output, 'network.@device[-1].mtu', dev.mtu);
			if (dev.peer_name)
				uci_set_string(output, 'network.@device[-1].peer_name', dev.peer_name);
			if (dev.ifname)
				uci_set_string(output, 'network.@device[-1].ifname', dev.ifname);
			if (dev.vid)
				uci_set_string(output, 'network.@device[-1].vid', dev.vid);
			if (dev.enabled != null)
				uci_set_string(output, 'network.@device[-1].enabled', dev.enabled);
			if (dev.ipv6 != null)
				uci_set_string(output, 'network.@device[-1].ipv6', dev.ipv6);

			for (let mapping in dev.egress_qos_mapping ?? [])
				uci_list_string(output, 'network.@device[-1].egress_qos_mapping', mapping);

			if (dev.ports)
				for (let port in dev.ports)
					uci_list_string(output, 'network.@device[-1].ports', port);

			if (dev.autoneg != null)
				uci_set_string(output, 'network.@device[-1].autoneg', dev.autoneg);
			if (dev.speed)
				uci_set_string(output, 'network.@device[-1].speed', dev.speed);
			if (dev.duplex)
				uci_set_string(output, 'network.@device[-1].duplex', dev.duplex);
			if (dev.eee != null)
				uci_set_string(output, 'network.@device[-1].eee', dev.eee);

			if (dev.igmp_snooping != null)
				uci_set_string(output, 'network.@device[-1].igmp_snooping', dev.igmp_snooping);
			if (dev.rpfilter)
				uci_set_string(output, 'network.@device[-1].rpfilter', dev.rpfilter);
			if (dev.proxy_arp)
				uci_set_string(output, 'network.@device[-1].proxy_arp', dev.proxy_arp);
			if (dev.drop_unsolicited_na)
				uci_set_string(output, 'network.@device[-1].drop_unsolicited_na', dev.drop_unsolicited_na);
			if (dev.unicast_flood != null)
				uci_set_string(output, 'network.@device[-1].unicast_flood', dev.unicast_flood);
			if (dev.broadcast_flood != null)
				uci_set_string(output, 'network.@device[-1].broadcast_flood', dev.broadcast_flood);
			if (dev.stp != null)
				uci_set_string(output, 'network.@device[-1].stp', dev.stp);
			if (dev.priority)
				uci_set_string(output, 'network.@device[-1].priority', dev.priority);
			if (dev.hello_time)
				uci_set_string(output, 'network.@device[-1].hello_time', dev.hello_time);
			if (dev.max_age)
				uci_set_string(output, 'network.@device[-1].max_age', dev.max_age);
			if (dev.forward_delay)
				uci_set_string(output, 'network.@device[-1].forward_delay', dev.forward_delay);

			if (dev.dadtransmits)
				uci_set_string(output, 'network.@device[-1].dadtransmits', dev.dadtransmits);
			if (dev.retranstime)
				uci_set_string(output, 'network.@device[-1].retranstime', dev.retranstime);
			if (dev.rtrsolicitinterval)
				uci_set_string(output, 'network.@device[-1].rtrsolicitinterval', dev.rtrsolicitinterval);
			if (dev.rtrsolicits != null)
				uci_set_string(output, 'network.@device[-1].rtrsolicits', dev.rtrsolicits);
		}

		return;
	}

	generate_devices();
}
uci_comment(output, '# generated by device.uc');
render_config();
