function render_config() {
	/**
	 * Generates /etc/config/dnsprobe sections from
	 * Device.IP.Interface.{i}.X_UBBF_DNSProbe. Only upstream interfaces
	 * with an enabled probe produce a section; the intent is to kick
	 * the WAN DHCP client when the ISP-supplied resolvers stop
	 * answering (MVP-2039 and MVP-2297).
	 *
	 * The daemon at /usr/bin/dnsprobe consumes this UCI file.
	 */
	function generate_dnsprobe() {
		let any_enabled = false;

		let interfaces = ubbf_instances(config, 'Device.IP.Interface');

		for (let iface in interfaces) {
			if (!ubbf_to_bool(iface.Upstream))
				continue;

			let probe = iface.X_UBBF_DNSProbe;
			if (!probe || !ubbf_to_bool(probe.Enable))
				continue;

			let host = probe.Host;
			if (!host || host == '')
				continue;

			let iface_name = iface.Name;
			if (!iface_name || iface_name == '')
				continue;

			let section_name = ubbf.name_sanitise(iface_name);

			any_enabled = true;

			uci_named_section(output, `dnsprobe.${section_name}`, 'probe');
			uci_set_string(output, `dnsprobe.${section_name}.interface`, iface_name);
			uci_set_string(output, `dnsprobe.${section_name}.host`, host);

			let interval = ubbf_to_int(probe.Interval);
			if (interval != null && interval > 0)
				uci_set_number(output, `dnsprobe.${section_name}.interval`, interval);

			let timeout = ubbf_to_int(probe.Timeout);
			if (timeout != null && timeout > 0)
				uci_set_number(output, `dnsprobe.${section_name}.timeout`, timeout);

			let fail_threshold = ubbf_to_int(probe.FailThreshold);
			if (fail_threshold != null && fail_threshold > 0)
				uci_set_number(output, `dnsprobe.${section_name}.fail_threshold`, fail_threshold);

			let cooldown = ubbf_to_int(probe.Cooldown);
			if (cooldown != null && cooldown >= 0)
				uci_set_number(output, `dnsprobe.${section_name}.cooldown`, cooldown);

			let family = probe.Family;
			if (family && family != '')
				uci_set_string(output, `dnsprobe.${section_name}.family`, lc(family));
		}

		services.set_enabled('dnsprobe', any_enabled);
	}

	generate_dnsprobe();
}
uci_comment(output, '# generated by dnsprobe.uc');
render_config();
