function render_config() {
const STATE_PATH = '/tmp/ubbf/firewall-alg.json';

// Per-protocol mapping between TR-181 ConnectionTracking sub-objects
// and the netfilter helper machinery.  `default_port` is the well-known
// port the kernel module probes for when no Ports value is set.  `params`
// maps TR-181 parameter names to /sys/module/<module>/parameters/<key>;
// `sysctl` maps TR-181 parameter names to /proc/sys/net/netfilter/<key>.
const algs = [
	{
		name: 'sip', tr181: 'SIP',
		module: 'nf_conntrack_sip', nat_module: 'nf_nat_sip',
		default_port: '5060',
		params: {
			DirectMedia: 'sip_direct_media',
			DirectSignaling: 'sip_direct_signalling',
			ExternalMedia: 'sip_external_media'
		},
		sysctl: {
			TimeOut: 'nf_conntrack_sip_timeout'
		}
	},
	{
		name: 'ftp', tr181: 'FTP',
		module: 'nf_conntrack_ftp', nat_module: 'nf_nat_ftp',
		default_port: '21',
		params: { Loose: 'loose' }
	},
	{
		name: 'h323', tr181: 'H323',
		module: 'nf_conntrack_h323', nat_module: 'nf_nat_h323',
		default_port: '1720',
		params: {
			RegistrationRequestTTL: 'default_rrq_ttl',
			GKRoutedOnly: 'gkrouted_only',
			CallForwardFilter: 'callforward_filter'
		}
	},
	{
		name: 'pptp', tr181: 'PPTP',
		module: 'nf_conntrack_pptp', nat_module: 'nf_nat_pptp',
		default_port: '1723'
	},
	{
		name: 'tftp', tr181: 'TFTP',
		module: 'nf_conntrack_tftp', nat_module: 'nf_nat_tftp',
		default_port: '69'
	},
	{
		name: 'irc', tr181: 'IRC',
		module: 'nf_conntrack_irc', nat_module: 'nf_nat_irc',
		default_port: '6667',
		params: {
			MAXDCCChannels: 'max_dcc_channels',
			DCCTimeout: 'dcc_timeout'
		}
	}
];

/**
 * Normalises a TR-181 Ports value into a comma-separated port list for
 * modprobe.  The schema types Ports as INT but the XML defines it as a
 * list, so callers may store either "21" or "21,2121".  The sentinel
 * "0" (the schema default) is treated as "no override" and yields the
 * empty string so the kernel module probes for its built-in default.
 *
 * @param {string|null} ports - raw TR-181 Ports value
 * @returns {string} comma-separated port list, or '' when unset
 */
function ports_normalise(ports) {
	if (!ports || ports == '' || ports == '0')
		return '';
	let parts = csv_to_list(ports, '0');
	return join(',', parts);
}

/**
 * Coerces a TR-181 value into the form the kernel module parameter
 * expects.  Booleans become "1"/"0"; everything else passes through.
 * Caller is responsible for skipping unset values.
 *
 * @param {string} value - TR-181 stringified value
 * @param {boolean} as_bool - true when the kernel param is a bool
 * @returns {string} coerced value
 */
function param_coerce(value, as_bool) {
	if (as_bool)
		return ubbf_to_bool(value) ? '1' : '0';
	return value;
}

/**
 * Builds the per-ALG runtime state entry consumed by
 * /usr/libexec/ubbf/fw-alg-apply.  Disabled entries still carry their
 * module/nat_module so the reconciler can unload anything left over from
 * a previous apply.
 *
 * @param {object} spec - one entry from the `algs` table
 * @param {object} cfg - matching ConnectionTracking.<X> config or null
 * @returns {object} state record
 */
function alg_entry_build(spec, cfg) {
	let entry = {
		name: spec.name,
		module: spec.module,
		nat_module: spec.nat_module ?? null,
		enable: ubbf_to_bool(cfg?.Enable),
		ports: ports_normalise(cfg?.Ports),
		params: {},
		sysctl: {}
	};

	for (let tr181_key, sys_key in (spec.params ?? {})) {
		let v = cfg?.[tr181_key];
		if (v == null || v == '')
			continue;
		let as_bool = (tr181_key == 'DirectMedia' ||
		               tr181_key == 'DirectSignaling' ||
		               tr181_key == 'ExternalMedia' ||
		               tr181_key == 'Loose' ||
		               tr181_key == 'GKRoutedOnly' ||
		               tr181_key == 'CallForwardFilter');
		entry.params[sys_key] = param_coerce(v, as_bool);
	}

	for (let tr181_key, sys_key in (spec.sysctl ?? {})) {
		let v = cfg?.[tr181_key];
		if (v == null || v == '' || v == '0')
			continue;
		entry.sysctl[sys_key] = v;
	}

	return entry;
}

let ct = ubbf_get(config, 'Device.Firewall.ConnectionTracking') ?? {};
let entries = [];

for (let spec in algs)
	push(entries, alg_entry_build(spec, ct[spec.tr181]));

let sysctl = {};
let max_sessions = ubbf_to_int(ubbf_get(config, 'Device.NAT')?.X_UBBF_MaxSessions);
if (max_sessions > 0)
	sysctl.nf_conntrack_max = sprintf('%d', max_sessions);

fs.mkdir('/tmp/ubbf', 0755);
fs.writefile(STATE_PATH, sprintf("%.J\n", { alg: entries, sysctl }));

// fw-alg-apply is a one-shot reconciler.  Enable+start it on every apply
// so kernel module presence and runtime params stay in sync with the
// rendered side-car.  When all ALGs are disabled it still runs and tears
// down any module the previous apply had loaded.
services.set_enabled('ubbf-fw-alg', true);
}
uci_comment(output, '# generated by firewall-conntrack.uc');
render_config();
