function render_config() {
const DOS_NFT_PATH = '/tmp/ubbf/firewall-dos.nft';

/**
 * Resolves the currently active Firewall Level.
 *
 * Device.Firewall.Config determines which pointer is followed:
 * "Advanced" -> AdvancedLevel, "Policy" -> PolicyLevel. Falls back to
 * the first iterated Level if neither pointer is set or the reference
 * fails to resolve.
 *
 * @param {object} firewall - Device.Firewall subtree
 * @returns {object|null} active Level object or null if none exist
 */
function active_level(firewall) {
	let ref = (firewall.Config == 'Policy')
		? firewall.PolicyLevel
		: firewall.AdvancedLevel;

	if (ref && ref != '') {
		let level = ubbf_get(config, ref);
		if (level)
			return level;
	}

	let levels = ubbf_instances(config, 'Device.Firewall.Level');
	for (let level in levels)
		return level;

	return null;
}

/**
 * Generates UCI firewall defaults section.
 */
function generate_defaults() {
	let firewall = ubbf_get(config, 'Device.Firewall');
	let level = firewall ? active_level(firewall) : null;
	let dos = firewall?.X_UBBF_DoSProtection ?? {};

	let forward = level ? target_to_uci(level.DefaultPolicy) : 'REJECT';
	let syn_flood = ubbf_to_bool(dos.SynFloodProtection ?? "true");
	let drop_invalid = ubbf_to_bool(dos.DropInvalidPackets ?? "true");

	uci_section(output, 'firewall defaults');
	uci_set_boolean(output, 'firewall.@defaults[-1].syn_flood', syn_flood);
	uci_set_boolean(output, 'firewall.@defaults[-1].drop_invalid', drop_invalid);
	uci_set_string(output, 'firewall.@defaults[-1].input', 'REJECT');
	uci_set_string(output, 'firewall.@defaults[-1].output', 'ACCEPT');
	uci_set_string(output, 'firewall.@defaults[-1].forward', forward);

	if (level && ubbf_to_bool(level.DefaultLogPolicy))
		uci_set_boolean(output, 'firewall.@defaults[-1].log', true);
}

/**
 * Writes the nftables include consumed by fw4 chain-prepend hook on the
 * global input chain. The file holds per-upstream-device, iifname-scoped
 * rules that must fire BEFORE fw4's ct-state-established accept:
 * IcmpRateLimit (rate over N/second drop) and DropMalformedTCP (XMAS,
 * NULL, SYN+FIN flag pattern drops). The file is regenerated on every
 * render; absent when no toggle requests it.
 *
 * Why chain-prepend input and not chain-prepend input_<zone>: fw4 emits
 * `ct state vmap { established : accept, ... }` at the start of the
 * global input chain, BEFORE jumping into the per-zone input_<zone>
 * chain. A single-source ICMP flood is a single conntrack flow; once
 * the first echo is accepted, every subsequent packet matches
 * established and bypasses per-zone rate-limit rules. Prepending on
 * the global input chain (and scoping by iifname) puts the limit
 * before the ct-state check.
 *
 * @param {object} dos - Device.Firewall.X_UBBF_DoSProtection subtree
 * @param {string[]} upstream_devices - L2 device names for upstream zones
 * @returns {boolean} true when the file holds at least one rule
 */
function generate_dos_nft(dos, upstream_devices) {
	let icmp_rate_limit = ubbf_to_bool(dos.IcmpRateLimit);
	let drop_malformed_tcp = ubbf_to_bool(dos.DropMalformedTCP);

	if (length(upstream_devices) == 0 || (!icmp_rate_limit && !drop_malformed_tcp)) {
		fs.unlink(DOS_NFT_PATH);
		return false;
	}

	let lines = [
		'# generated by firewall.uc -- Device.Firewall.X_UBBF_DoSProtection'
	];

	for (let dev in upstream_devices) {
		if (icmp_rate_limit) {
			push(lines, `iifname "${dev}" meta nfproto ipv4 icmp type echo-request limit rate over 10/second drop comment "ubbf-dos: WAN ICMPv4 echo rate-limit"`);
			push(lines, `iifname "${dev}" meta nfproto ipv6 icmpv6 type echo-request limit rate over 10/second drop comment "ubbf-dos: WAN ICMPv6 echo rate-limit"`);
		}
		if (drop_malformed_tcp) {
			push(lines, `iifname "${dev}" tcp flags & (fin|syn|rst|psh|ack|urg) == fin|psh|urg drop comment "ubbf-dos: drop XMAS TCP"`);
			push(lines, `iifname "${dev}" tcp flags & (fin|syn|rst|psh|ack|urg) == 0x0 drop comment "ubbf-dos: drop NULL TCP"`);
			push(lines, `iifname "${dev}" tcp flags & (syn|fin) == syn|fin drop comment "ubbf-dos: drop SYN-FIN TCP"`);
		}
	}

	fs.mkdir('/tmp/ubbf', 0755);
	fs.writefile(DOS_NFT_PATH, join('\n', lines) + '\n');
	return true;
}

/**
 * Returns the static IPv4 subnets of the downstream IP interfaces.
 *
 * @returns {string[]} subnets in address/prefix-length notation
 */
function downstream_subnets_get() {
	let subnets = [];

	for (let iface in ubbf_instances(config, 'Device.IP.Interface')) {
		if (ubbf_to_bool(iface.Upstream))
			continue;

		for (let addr in ubbf_instances(iface, 'IPv4Address')) {
			if (!ubbf_to_bool(addr.Enable) || !addr.IPAddress)
				continue;
			if (lc(addr.AddressingType || 'Static') != 'static')
				continue;

			let cidr = ubbf.netmask_to_cidr(addr.SubnetMask);
			if (cidr)
				push(subnets, `${addr.IPAddress}/${cidr}`);
		}
	}

	return subnets;
}

/**
 * Generates UCI firewall zones from reconciled InterfaceSetting instances.
 * Applies masquerade from Device.NAT.InterfaceSetting.
 */
function generate_zones() {
	let firewall = ubbf_get(config, 'Device.Firewall');
	let iface_settings = ubbf_instances(config, 'Device.Firewall.InterfaceSetting');
	let nat_settings = ubbf_instances(config, 'Device.NAT.InterfaceSetting');

	let level = firewall ? active_level(firewall) : null;
	let forward = level ? target_to_uci(level.DefaultPolicy) : 'REJECT';

	let nat_map = {};
	for (let ns in nat_settings) {
		if (!ns.Interface || ns.Interface == '')
			continue;
		nat_map[ns.Interface] = ubbf_to_bool(ns.Enable);
	}

	let masq_subnets = downstream_subnets_get();

	for (let ifs in iface_settings) {
		if (!ubbf_to_bool(ifs.Enable))
			continue;

		let name = interface_to_name(config, ifs.Interface);
		if (!name)
			continue;

		let stealth = ubbf_to_bool(ifs.StealthMode);
		let input = stealth ? 'DROP' : 'REJECT';

		uci_named_section(output, `firewall.${name}`, 'zone');
		uci_set_string(output, `firewall.${name}.name`, name);
		uci_list_string(output, `firewall.${name}.network`, name);
		uci_set_string(output, `firewall.${name}.input`, input);
		uci_set_string(output, `firewall.${name}.output`, 'ACCEPT');
		uci_set_string(output, `firewall.${name}.forward`, forward);

		if (nat_map[ifs.Interface]) {
			uci_set_boolean(output, `firewall.${name}.masq`, true);
			uci_set_boolean(output, `firewall.${name}.mtu_fix`, true);
			// Masquerade also binds the router's own WAN connections to the
			// WAN address, and the kernel deletes those conntrack entries
			// when the address goes away; the ACS session then stalls after
			// a WAN restart until the agent sends again.
			for (let subnet in masq_subnets)
				uci_list_string(output, `firewall.${name}.masq_src`, subnet);
		}

		let iface_obj = ubbf_get(config, ifs.Interface);
		let l2_dev = iface_obj ? lower_layer_resolve_vlan(config, iface_obj.LowerLayers) : null;
		if (l2_dev) {
			if (ubbf_to_bool(ifs.IPv4SpoofingProtection))
				device_state_set(render_state, l2_dev, 'rpfilter', '1');
			if (ubbf_to_bool(ifs.IPv6SpoofingProtection))
				device_state_set(render_state, l2_dev, 'drop_unsolicited_na', '1');
		}
	}
}

/**
 * Generates static per-zone rules (IGMP, MLD, ICMPv6) and conditional ping rules.
 */
function generate_per_zone_rules() {
	let firewall = ubbf_get(config, 'Device.Firewall');
	let respond_to_ping = firewall ? ubbf_to_bool(firewall.X_UBBF_RespondToPing) : true;
	let dos = firewall?.X_UBBF_DoSProtection ?? {};
	let drop_multicast_wan = ubbf_to_bool(dos.DropMulticastWAN ?? "true");
	let iface_settings = ubbf_instances(config, 'Device.Firewall.InterfaceSetting');
	let upstream_devices = [];

	for (let ifs in iface_settings) {
		if (!ubbf_to_bool(ifs.Enable))
			continue;

		let zone = interface_to_name(config, ifs.Interface);
		if (!zone)
			continue;

		// X_UBBF_RespondToPing=false silences ICMP echo replies on
		// upstream (WAN-facing) zones only. LAN zones keep responding
		// per their own IPv4/IPv6AcceptICMPEchoRequest setting.
		let iface_ref = ubbf_get(config, ifs.Interface);
		let is_upstream = iface_ref ? ubbf_to_bool(iface_ref.Upstream) : false;
		let suppress_ping = is_upstream && !respond_to_ping;

		if (is_upstream) {
			let dev = lower_layer_resolve_vlan(config, iface_ref?.LowerLayers);
			if (dev)
				push(upstream_devices, dev);
		}

		uci_section(output, 'firewall rule');
		uci_set_string(output, 'firewall.@rule[-1].name', `Allow-IGMP-${zone}`);
		uci_set_string(output, 'firewall.@rule[-1].src', zone);
		uci_set_string(output, 'firewall.@rule[-1].proto', 'igmp');
		uci_set_string(output, 'firewall.@rule[-1].family', 'ipv4');
		uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');

		uci_section(output, 'firewall rule');
		uci_set_string(output, 'firewall.@rule[-1].name', `Allow-MLD-${zone}`);
		uci_set_string(output, 'firewall.@rule[-1].src', zone);
		uci_set_string(output, 'firewall.@rule[-1].proto', 'icmp');
		uci_set_string(output, 'firewall.@rule[-1].src_ip', 'fe80::/10');
		uci_set_string(output, 'firewall.@rule[-1].icmp_type', '143/0');
		uci_set_string(output, 'firewall.@rule[-1].family', 'ipv6');
		uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');

		uci_section(output, 'firewall rule');
		uci_set_string(output, 'firewall.@rule[-1].name', `Allow-ICMPv6-Input-${zone}`);
		uci_set_string(output, 'firewall.@rule[-1].src', zone);
		uci_set_string(output, 'firewall.@rule[-1].proto', 'icmp');
		for (let icmp_type in [ 'destination-unreachable', 'packet-too-big',
		                        'time-exceeded', 'bad-header', 'unknown-header-type',
		                        'router-solicitation', 'neighbour-solicitation',
		                        'router-advertisement', 'neighbour-advertisement' ])
			uci_list_string(output, 'firewall.@rule[-1].icmp_type', icmp_type);
		uci_set_string(output, 'firewall.@rule[-1].limit', '1000/sec');
		uci_set_string(output, 'firewall.@rule[-1].family', 'ipv6');
		uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');

		uci_section(output, 'firewall rule');
		uci_set_string(output, 'firewall.@rule[-1].name', `Allow-ICMPv6-Forward-${zone}`);
		uci_set_string(output, 'firewall.@rule[-1].src', zone);
		uci_set_string(output, 'firewall.@rule[-1].dest', '*');
		uci_set_string(output, 'firewall.@rule[-1].proto', 'icmp');
		for (let icmp_type in [ 'echo-request', 'echo-reply', 'destination-unreachable',
		                        'packet-too-big', 'time-exceeded', 'bad-header',
		                        'unknown-header-type' ])
			uci_list_string(output, 'firewall.@rule[-1].icmp_type', icmp_type);
		uci_set_string(output, 'firewall.@rule[-1].limit', '1000/sec');
		uci_set_string(output, 'firewall.@rule[-1].family', 'ipv6');
		uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');

		if (ubbf_to_bool(ifs.IPv4AcceptICMPEchoRequest) && !suppress_ping) {
			uci_section(output, 'firewall rule');
			uci_set_string(output, 'firewall.@rule[-1].name', `Allow-Ping-${zone}`);
			uci_set_string(output, 'firewall.@rule[-1].src', zone);
			uci_set_string(output, 'firewall.@rule[-1].proto', 'icmp');
			uci_set_string(output, 'firewall.@rule[-1].icmp_type', 'echo-request');
			uci_set_string(output, 'firewall.@rule[-1].family', 'ipv4');
			uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');
		}

		if (ubbf_to_bool(ifs.IPv6AcceptICMPEchoRequest) && !suppress_ping) {
			uci_section(output, 'firewall rule');
			uci_set_string(output, 'firewall.@rule[-1].name', `Allow-ICMPv6-Echo-${zone}`);
			uci_set_string(output, 'firewall.@rule[-1].src', zone);
			uci_set_string(output, 'firewall.@rule[-1].proto', 'icmp');
			uci_set_string(output, 'firewall.@rule[-1].icmp_type', 'echo-request');
			uci_set_string(output, 'firewall.@rule[-1].family', 'ipv6');
			uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');
		}

		// Multicast drop is a zone-input rule; multicast WAN packets
		// rarely have established conntrack state so dropping inside
		// the per-zone input chain is fine. IcmpRateLimit and
		// DropMalformedTCP need to run before ct-state-established
		// and are emitted via the global chain-prepend include below.
		if (is_upstream && drop_multicast_wan) {
			uci_section(output, 'firewall rule');
			uci_set_string(output, 'firewall.@rule[-1].name', `Drop-Multicast-WAN-${zone}-v4`);
			uci_set_string(output, 'firewall.@rule[-1].src', zone);
			uci_set_string(output, 'firewall.@rule[-1].dest_ip', '224.0.0.0/4');
			uci_set_string(output, 'firewall.@rule[-1].family', 'ipv4');
			uci_set_string(output, 'firewall.@rule[-1].target', 'DROP');

			uci_section(output, 'firewall rule');
			uci_set_string(output, 'firewall.@rule[-1].name', `Drop-Multicast-WAN-${zone}-v6`);
			uci_set_string(output, 'firewall.@rule[-1].src', zone);
			uci_set_string(output, 'firewall.@rule[-1].dest_ip', 'ff00::/8');
			uci_set_string(output, 'firewall.@rule[-1].family', 'ipv6');
			uci_set_string(output, 'firewall.@rule[-1].target', 'DROP');
		}

		if (ubbf_to_bool(ifs.IPv6PassThroughICMPEchoRequest)) {
			uci_section(output, 'firewall rule');
			uci_set_string(output, 'firewall.@rule[-1].name', `Allow-ICMPv6-Echo-Fwd-${zone}`);
			uci_set_string(output, 'firewall.@rule[-1].src', zone);
			uci_set_string(output, 'firewall.@rule[-1].dest', '*');
			uci_set_string(output, 'firewall.@rule[-1].proto', 'icmp');
			uci_set_string(output, 'firewall.@rule[-1].icmp_type', 'echo-request');
			uci_set_string(output, 'firewall.@rule[-1].family', 'ipv6');
			uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');
		}
	}

	if (generate_dos_nft(dos, upstream_devices)) {
		uci_section(output, 'firewall include');
		uci_set_string(output, 'firewall.@include[-1].type', 'nftables');
		uci_set_string(output, 'firewall.@include[-1].path', DOS_NFT_PATH);
		uci_set_string(output, 'firewall.@include[-1].position', 'chain-prepend');
		uci_set_string(output, 'firewall.@include[-1].chain', 'input');
	}
}

let firewall = ubbf_get(config, 'Device.Firewall');
if (!firewall)
	return;

// Tie /etc/init.d/firewall start/stop to Firewall.Enable. Using
// start/stop (not restart) avoids tearing down existing connections
// on every apply when the state is unchanged.
let firewall_enabled = ubbf_to_bool(firewall.Enable);
services.set_enabled('firewall', firewall_enabled);

if (!firewall_enabled)
	return;

// Pre-flag ADMZ activity for firewall-dmz.uc which precedes
// firewall-admz.uc in the include order. The flag matches the same
// configured-enable predicate that firewall-admz.uc tests, so classic
// DMZ stays suppressed even when ADMZ is temporarily in Enabled_NoWANIP
// (WAN down). Otherwise classic DMZ would briefly flap back into the
// fw4 ruleset on every WAN bounce.
let admz_cfg = ubbf_get(config, 'Device.NAT.X_UBBF_IPPassthrough');
if (admz_cfg && ubbf_to_bool(admz_cfg.Enable) &&
    admz_cfg.AdvancedDMZhost && admz_cfg.AdvancedDMZhost != '')
	render_state.admz_active = true;

generate_defaults();
generate_zones();
tryinclude("firewall-chains.uc");
generate_per_zone_rules();
tryinclude("firewall-services.uc");
tryinclude("firewall-pinholes.uc");
tryinclude("firewall-dmz.uc");
tryinclude("firewall-acl.uc");
tryinclude("firewall-nat.uc");
tryinclude("firewall-admz.uc");
tryinclude("firewall-conntrack.uc");
}
uci_comment(output, '# generated by firewall.uc');
render_config();
