function render_config() {

	/**
	 * Resolves an interface reference to its underlying device name.
	 *
	 * @param {string} iface_ref - Interface path reference
	 * @returns {string|null} Device name or null if not found
	 */
	function resolve_interface_device(iface_ref) {
		if (!iface_ref)
			return null;

		let iface = ubbf_get(config, iface_ref);
		if (!iface?.Name)
			return null;

		// Must match the netdev the IP interface actually rides (ip.uc
		// ifname, netifd l3_device): the NDP sysctls are per-netdev, and
		// the TR-181 getter reads them from the l3_device. The plain
		// resolver lands on the bridge (br-lan) while the interface uses
		// the VLAN device on top of it (br-lanv0).
		let device = lower_layer_resolve_vlan(config, iface.LowerLayers);
		if (device)
			return device;

		return iface.Name;
	}

	/**
	 * Populates device render state with NDP settings.
	 *
	 * @param {array} instances - InterfaceSetting instances
	 */
	function populate_ndp_settings(instances) {
		for (let setting in instances) {
			if (!setting || !ubbf_to_bool(setting.Enable))
				continue;

			let device = resolve_interface_device(setting.Interface);
			if (!device)
				continue;

			let dad_transmits = ubbf_to_int(setting.DADTransmits);
			if (dad_transmits != null)
				device_state_set(render_state, device, 'dadtransmits', sprintf('%d', dad_transmits));

			let retrans_timer = ubbf_to_int(setting.RetransTimer);
			if (retrans_timer != null)
				device_state_set(render_state, device, 'retranstime', sprintf('%d', retrans_timer));

			let rtr_solicit_interval = ubbf_to_int(setting.RtrSolicitationInterval);
			if (rtr_solicit_interval != null) {
				// TR-181 RtrSolicitationInterval is in ms; the Linux
				// router_solicitation_interval sysctl is in seconds.
				// Floor to 1 s so a sub-second TR-181 value still
				// produces a valid sysctl write.
				let interval_sec = int(rtr_solicit_interval / 1000);
				if (interval_sec < 1)
					interval_sec = 1;
				device_state_set(render_state, device, 'rtrsolicitinterval', sprintf('%d', interval_sec));
			}

			let rs_enable = ubbf_to_bool(setting.RSEnable);
			let max_rtr_solicits = ubbf_to_int(setting.MaxRtrSolicitations);

			if (rs_enable == false) {
				device_state_set(render_state, device, 'rtrsolicits', '0');
			} else if (max_rtr_solicits != null) {
				device_state_set(render_state, device, 'rtrsolicits', sprintf('%d', max_rtr_solicits));
			}
		}
	}

	let nd = ubbf_get(config, 'Device.NeighborDiscovery');
	if (!nd || !ubbf_to_bool(nd.Enable))
		return;

	let settings = ubbf_instances(config, 'Device.NeighborDiscovery.InterfaceSetting');
	populate_ndp_settings(settings);

}
uci_comment(output, '# generated by neighbordiscovery.uc');
render_config();
