function render_config() {
	services.set_enabled('nlbwmon', true);


	uci_named_section(output, 'nlbwmon.nlbwmon', 'nlbwmon');
	uci_set_string(output, 'nlbwmon.nlbwmon.database_directory', '/tmp/nlbwmon');
	uci_set_string(output, 'nlbwmon.nlbwmon.commit_interval', '24d');
	uci_set_number(output, 'nlbwmon.nlbwmon.database_generations', 1);

	uci_delete(output, 'nlbwmon.nlbwmon.local_network');
	uci_list_string(output, 'nlbwmon.nlbwmon.local_network', '10.0.0.0/8');
	uci_list_string(output, 'nlbwmon.nlbwmon.local_network', '172.16.0.0/12');
	uci_list_string(output, 'nlbwmon.nlbwmon.local_network', '192.168.0.0/16');

}
uci_comment(output, '# generated by nlbwmon.uc');
render_config();
