function render_config() {
	/**
	 * Generates UCI sections for the PCP service from the
	 * Device.PCP data model and toggles ubbf-pcp based on whether
	 * any enabled mapping was emitted.
	 *
	 * @returns {string} UCI batch output for pcp
	 */
	function generate_pcp() {
		let any_enabled = false;

		let clients = ubbf_instances(config, 'Device.PCP.Client');

		for (let client in clients) {
			if (!ubbf_to_bool(client.Enable))
				continue;

			let servers = ubbf_instances(config, client['.path'] + '.Server');

			for (let server in servers) {
				if (!ubbf_to_bool(server.Enable))
					continue;

				let addr = server.ServerNameOrAddress;
				if (!addr || addr == '')
					continue;

				let section = ubbf.name_sanitise(sprintf('pcp_%s_%s',
					client['.instance'], server['.instance']));

				uci_named_section(output, `pcp.${section}`, 'server');
				uci_set_string(output, `pcp.${section}.address`, addr);
				uci_set_string(output, `pcp.${section}.client`, client['.instance']);
				uci_set_string(output, `pcp.${section}.server`, server['.instance']);

				if (server.PreferredLifetime && server.PreferredLifetime != '0')
					uci_set_number(output, `pcp.${section}.preferred_lifetime`,
						ubbf_to_int(server.PreferredLifetime));

				if (server.MaximumFilters && server.MaximumFilters != '0')
					uci_set_number(output, `pcp.${section}.max_filters`,
						ubbf_to_int(server.MaximumFilters));

				let mappings = ubbf_instances(config,
					server['.path'] + '.InboundMapping');

				for (let mapping in mappings) {
					if (!ubbf_to_bool(mapping.Enable))
						continue;

					let map_section = ubbf.name_sanitise(sprintf('map_%s_%s_%s',
						client['.instance'],
						server['.instance'],
						mapping['.instance']));

					uci_named_section(output, `pcp.${map_section}`, 'mapping');
					uci_set_string(output, `pcp.${map_section}.server`, section);
					uci_set_string(output, `pcp.${map_section}.instance`, mapping['.instance']);
					uci_set_number(output, `pcp.${map_section}.internal_port`,
						ubbf_to_int(mapping.InternalPort));
					uci_set_number(output, `pcp.${map_section}.protocol`,
						ubbf_to_int(mapping.ProtocolNumber));
					uci_set_number(output, `pcp.${map_section}.lifetime`,
						ubbf_to_int(mapping.Lifetime));

					if (mapping.ThirdPartyAddress && mapping.ThirdPartyAddress != '')
						uci_set_string(output, `pcp.${map_section}.third_party`,
							mapping.ThirdPartyAddress);

					if (mapping.Description && mapping.Description != '')
						uci_set_string(output, `pcp.${map_section}.description`,
							mapping.Description);

					let filters = ubbf_instances(config,
						mapping['.path'] + '.Filter');

					let filt_list = [];
					for (let filter in filters) {
						let ip = filter.RemoteHostIPAddress;
						let prefix = filter.PrefixLength ?? '128';
						if (ip && ip != '')
							push(filt_list, `${ip}/${prefix}`);
					}

					if (length(filt_list))
						for (let f in filt_list)
							uci_list_string(output, `pcp.${map_section}.filter`, f);

					any_enabled = true;
				}
			}
		}

		services.set_enabled('ubbf-pcp', any_enabled);
		return;
	}

	let pcp = ubbf_get(config, 'Device.PCP');
	if (!pcp || !ubbf_to_bool(pcp.Enable))
		return;

	generate_pcp();
}
uci_comment(output, '# generated by pcp.uc');
render_config();
