function render_config() {
	/**
	 * Generates a UCI network route section.
	 *
	 * @param {object} route_data - Route data model object
	 * @param {boolean} is_ipv6 - True for IPv6 route, false for IPv4
	 * @returns {string} UCI batch output for the route
	 */
	function generate_route(route_data, is_ipv6) {
		let section = is_ipv6 ? 'route6' : 'route';
		let iface_name = interface_to_name(config, route_data.Interface);

		uci_section(output, `network ${section}`);

		if (iface_name)
			uci_set_string(output, `network.@${section}[-1].interface`, iface_name);

		let target = is_ipv6 ? route_data.DestIPPrefix : route_data.DestIPAddress;
		if (target)
			uci_set_string(output, `network.@${section}[-1].target`, target);

		if (!is_ipv6 && route_data.DestSubnetMask)
			uci_set_string(output, `network.@${section}[-1].netmask`, route_data.DestSubnetMask);

		let gateway = is_ipv6 ? route_data.NextHop : route_data.GatewayIPAddress;
		if (gateway)
			uci_set_string(output, `network.@${section}[-1].gateway`, gateway);

		let metric = ubbf_to_int(route_data.ForwardingMetric);
		if (metric != null && metric >= 0)
			uci_set_number(output, `network.@${section}[-1].metric`, metric);

		let table = ubbf_to_int(route_data.ForwardingPolicy);
		if (table != null && table >= 0)
			uci_set_number(output, `network.@${section}[-1].table`, table);

		uci_set_boolean(output, `network.@${section}[-1].disabled`, !ubbf_to_bool(route_data.Enable));

		return;
	}

	/**
	 * Generates UCI route sections for all routers.
	 *
	 * @returns {string} Combined UCI batch output for all routes
	 */
	function generate_all_routes() {
		let routers = ubbf_instances(config, 'Device.Routing.Router');
		if (length(routers) == 0)
			return;


		for (let router in routers) {
			if (!router)
				continue;

			let inst = router['.instance'];

			for (let route in ubbf_instances(config, `Device.Routing.Router.${inst}.IPv4Forwarding`))
				generate_route(route, false);

			for (let route in ubbf_instances(config, `Device.Routing.Router.${inst}.IPv6Forwarding`))
				generate_route(route, true);
		}
	}

	let routers = ubbf_instances(config, 'Device.Routing.Router');
	if (length(routers) == 0)
		return;

	let has_routes = false;
	for (let router in routers) {
		if (!router) continue;
		let inst = router['.instance'];
		let ipv4_routes = ubbf_instances(config, `Device.Routing.Router.${inst}.IPv4Forwarding`);
		let ipv6_routes = ubbf_instances(config, `Device.Routing.Router.${inst}.IPv6Forwarding`);
		if (length(ipv4_routes) > 0 || length(ipv6_routes) > 0) {
			has_routes = true;
			break;
		}
	}

	if (!has_routes)
		return;

	generate_all_routes();
}
uci_comment(output, '# generated by routing.uc');
render_config();
