function render_config() {
	/**
	 * Generates UCI dropbear section for SSH server.
	 *
	 * @param {object} server_data - SSH server data model object
	 * @returns {string} UCI batch output for dropbear
	 */
	function generate_dropbear_instance(server_data) {
		if (!ubbf_to_bool(server_data.Enable))
			return;

		let port = ubbf_to_int(server_data.Port);
		if (!port)
			return;


		uci_comment(output, `## generate SSH instance ${server_data.Alias}`);
		uci_section(output, 'dropbear dropbear');
		uci_set_boolean(output, 'dropbear.@dropbear[-1].enable', true);
		uci_set_number(output, 'dropbear.@dropbear[-1].Port', ubbf_to_int(server_data.Port));
		uci_set_boolean(output, 'dropbear.@dropbear[-1].PasswordAuth', ubbf_to_bool(server_data.AllowPasswordLogin));
		uci_set_boolean(output, 'dropbear.@dropbear[-1].RootPasswordAuth', ubbf_to_bool(server_data.AllowRootPasswordLogin));
		uci_set_boolean(output, 'dropbear.@dropbear[-1].RootLogin', ubbf_to_bool(server_data.AllowRootLogin));
		uci_set_number(output, 'dropbear.@dropbear[-1].IdleTimeout', ubbf_to_int(server_data.IdleTimeout));
		uci_set_number(output, 'dropbear.@dropbear[-1].MaxAuthTries', ubbf_to_int(server_data.MaxAuthTries));
		uci_set_number(output, 'dropbear.@dropbear[-1].SSHKeepAlive', ubbf_to_int(server_data.KeepAlive));

		return;
	}

	/**
	 * Deploys the authorized keys that match the accepted key types and
	 * the minimum RSA size to /etc/dropbear/authorized_keys. Empties the
	 * file if no key qualifies.
	 */
	function deploy_authorized_keys() {
		let ssh = ubbf_get(config, 'Device.SSH');
		let accepted = csv_to_list(ssh?.X_UBBF_PubkeyAcceptedKeyTypes ?? join(',', ssh_keys.KEY_TYPES));
		let min_rsa_bits = ubbf_to_int(ssh?.X_UBBF_MinRSAKeyBits) ?? ssh_keys.MIN_RSA_BITS;

		let auth_keys = ubbf_instances(config, 'Device.SSH.AuthorizedKey');
		let lines = [];
		for (let inst, key_data in auth_keys) {
			if (!key_data.Key || key_data.Key == '')
				continue;
			if (!ssh_keys.key_acceptable(key_data.Key, accepted, min_rsa_bits)) {
				warn('ssh: not deploying AuthorizedKey %s: malformed, or not an accepted type or size', inst);
				continue;
			}
			push(lines, key_data.Key);
		}

		ubbf.write_file_atomic('/etc/dropbear/authorized_keys',
			length(lines) > 0 ? join('\n', lines) + '\n' : '');
	}

	let enable = ubbf_enabled(config, 'Device.SSH.Enable');
	services.set_enabled('dropbear', !!enable);
	deploy_authorized_keys();

	if (!enable)
		return;

	for (let inst, server_data in ubbf_instances(config, 'Device.SSH.Server'))
		generate_dropbear_instance(server_data);
}
uci_comment(output, '# generated by ssh.uc');
render_config();
