function render_config() {
	/**
	 * Generates UCI NTP client configuration.
	 *
	 * @param {object} time_config - Time data model object
	 * @returns {string} UCI batch output for NTP settings
	 */
	function generate_time_config(time_config) {

		uci_set_boolean(output, 'system.ntp.enabled', true);
		uci_set_string(output, 'system.@system[0].timezone', time_config.LocalTimeZone);

		uci_delete(output, 'system.ntp.server');

		let clients = ubbf_instances(config, 'Device.Time.Client');
		let client = clients?.[0];

		if (client && ubbf_to_bool(client.Enable)) {
			for (let server in csv_to_list(client.Servers))
				uci_list_string(output, 'system.ntp.server', server);
		} else {
			for (let key in [ 'NTPServer1', 'NTPServer2', 'NTPServer3' ]) {
				if (time_config[key])
					uci_list_string(output, 'system.ntp.server', time_config[key]);
			}
		}

		let servers = ubbf_instances(config, 'Device.Time.Server');
		let any_server_enabled = false;
		for (let inst, server_data in servers) {
			if (ubbf_to_bool(server_data?.Enable))
				any_server_enabled = true;
		}
		uci_set_boolean(output, 'system.ntp.enable_server', any_server_enabled);

		return;
	}

	/**
	 * Generates complete UCI time configuration.
	 *
	 * @param {object} time_config - Time data model object
	 * @returns {string} UCI batch output for time settings
	 */
	function generate_all(time_config) {
		return generate_time_config(time_config);
	}

	let time_config = ubbf_get(config, 'Device.Time');
	if (!time_config)
		return;

	let enable = ubbf_to_bool(time_config.Enable);
	services.set_enabled('sysntpd', enable);

	if (!enable)
		return;

	generate_all(time_config);
}
uci_comment(output, '# generated by time.uc');
render_config();
