function render_config() {
	let udpecho = ubbf_get(config, 'Device.IP.Diagnostics.UDPEchoConfig');
	if (!udpecho)
		return;

	let enable = ubbf_to_bool(udpecho.Enable);
	services.set_enabled('ubbf-udpecho', enable);

	if (!enable)
		return;

	// IANA echo protocol port (RFC 862) is the default when UDPPort is unset or zero.
	let port = ubbf_to_int(udpecho.UDPPort) || 7;
	let source_ip = udpecho.SourceIPAddress ?? '';
	let echo_plus = ubbf_to_bool(udpecho.EchoPlusEnabled);


	uci_named_section(output, 'ubbf.udpecho', 'udpecho');
	uci_set_boolean(output, 'ubbf.udpecho.enabled', true);
	uci_set_number(output, 'ubbf.udpecho.port', port);

	if (source_ip != '')
		uci_set_string(output, 'ubbf.udpecho.source_ip', source_ip);

	if (echo_plus)
		uci_set_boolean(output, 'ubbf.udpecho.echo_plus', true);

}
uci_comment(output, '# generated by udpecho.uc');
render_config();
