function render_config() {
	let ui = ubbf_get(config, 'Device.UserInterface');
	if (!ui)
		return;

	let http_access = ubbf_instances(config, 'Device.UserInterface.HTTPAccess');
	services.set_enabled('ubbf-ui', length(http_access) > 0);
	if (!length(http_access))
		return;

	/**
	 * Generates UCI webui server section and firewall rule.
	 *
	 * @param {string} inst - Instance number
	 * @param {object} data - HTTPAccess data model object
	 * @returns {string} UCI batch output for webui server
	 */
	function generate_server_instance(inst, data) {

		uci_section(output, 'webui server');
		uci_set_boolean(output, 'webui.@server[-1].enabled', ubbf_to_bool(data.Enable));
		uci_set_number(output, 'webui.@server[-1].port', ubbf_to_int(data.Port));
		uci_set_string(output, 'webui.@server[-1].protocol', lc(data.Protocol));
		uci_set_string(output, 'webui.@server[-1].tls_min_version', data.X_UBBF_TLSMinVersion ?? '1.2');

		if (data.Certificate)
			uci_set_string(output, 'webui.@server[-1].certificate', data.Certificate);
		if (data.PrivateKey)
			uci_set_string(output, 'webui.@server[-1].private_key', data.PrivateKey);

		if (data.Interface) {
			let iface = ubbf_get(config, data.Interface);
			if (iface?.Name)
				uci_set_string(output, 'webui.@server[-1].interface', iface.Name);
		}

		return;
	}

	for (let inst, data in http_access)
		generate_server_instance(inst, data);
}
uci_comment(output, '# generated by userinterface.uc');
render_config();
