#!/usr/bin/env python3
"""Emits schemas/constraints.uc from the TR-181 spec.

Unlike generate_ucode_schemas.py this never rewrites a curated schema file:
it produces one additive artefact that datamodel.uc merges over them, so the
hand-maintained state under schemas/ is untouched.

The output is restricted to parameters the shipped model actually declares,
so the artefact stays a fraction of the full spec, and to writable ones,
because a constraint the CPE never has to validate is dead weight in the VM.

Usage:
    generate_constraints.py --schema <dump.json> [--check]

The schema dump is what datamodel.uc exposes as `schema_readable`; the
session harness writes it with dump-schema.uc.
"""

import argparse
import json
import sys
from pathlib import Path

SPEC_DIR = Path(__file__).resolve().parent / "json_spec"
OUT = (Path(__file__).resolve().parent.parent
       / "files/usr/share/ucode/ubbf/schemas/constraints.uc")

HEADER = """\
// Generated by dm/generate_constraints.py from dm/json_spec/. Do not edit:
// the hand-maintained tables live in the per-domain schema files, and a
// constraints entry there is merged over anything stated here.
//
// Only parameters the shipped model declares and marks writable appear, so
// this is a fraction of what TR-181 states.

'use strict';

export const constraints = """

OBJECT_HEADER = """\
// Per-table facts. `addable: false` marks a table the CPE maintains itself,
// which a controller may read but not add to; `maxInstances` is the spec's
// maxEntries where it states a finite one.
export const object_meta = """

# TR-181 type names that carry a numeric range worth enforcing.
NUMERIC = {"int", "unsignedInt", "long", "unsignedLong"}


def spec_load():
    """Maps "<object path><Param>" to its record, and each object to its own."""
    params = {}
    objects = {}
    for path in sorted(SPEC_DIR.glob("*.json")):
        try:
            doc = json.loads(path.read_text())
        except (OSError, ValueError):
            continue
        obj = doc.get("object") or {}
        base = obj.get("path") or ""
        if not base:
            continue
        objects[base] = obj
        for param in obj.get("parameters") or []:
            name = param.get("name")
            if name:
                params[base + name] = param
    return params, objects


def object_meta_for(obj, is_table):
    """What the spec says about a table, as far as ubbf enforces it."""
    out = {}

    # A readOnly table is one the CPE maintains itself, so a controller
    # adding a row to it is an error rather than a request.
    if obj.get("access") == "readOnly":
        out["addable"] = False

    limit = obj.get("maxEntries")
    if is_table and limit is not None and str(limit).isdigit():
        out["maxInstances"] = int(limit)

    return out


def constraint_for(param):
    """The enforceable facts of one spec parameter, or an empty dict."""
    out = {}

    # In a list, enum, the range and the lengths apply to each item, and the
    # list lengths to the whole comma-separated value. A list is marked even
    # without other facts, because ubbf may type it as an integer and the
    # integer check must then run per item.
    is_list = bool(param.get("list"))
    if is_list:
        out["list"] = True
        for key, name in (("listMinLength", "list_min_length"),
                          ("listMaxLength", "list_max_length")):
            if param.get(key) is not None:
                out[name] = int(param[key])

    enums = param.get("enumerations")
    if isinstance(enums, list) and enums:
        out["enum"] = list(enums)

    ptype = param.get("type") or ""
    if ptype in NUMERIC:
        for key, name in (("minInclusive", "min"), ("maxInclusive", "max")):
            if param.get(key) is not None:
                out[name] = int(param[key])
        if param.get("ranges"):
            out["ranges"] = [list(r) for r in param["ranges"]]

    if ptype == "string":
        for key, name in (("minLength", "min_length"), ("maxLength", "max_length")):
            if param.get(key) is not None:
                out[name] = int(param[key])
        if param.get("lengths"):
            out["lengths"] = [list(r) for r in param["lengths"]]

    return out


def pattern_to_spec_path(pattern):
    """"Device.WiFi.Radio.{i}" -> "Device.WiFi.Radio.{i}." as the spec keys it."""
    return pattern + "."


def build(schema):
    spec, objects = spec_load()
    table = {}
    meta = {}

    for pattern, params in sorted((schema.get("objects") or {}).items()):
        base = pattern_to_spec_path(pattern)

        obj = objects.get(base)
        if obj is not None:
            got = object_meta_for(obj, pattern.endswith("{i}"))
            if got:
                meta[pattern] = got

        entry = {}
        for name, info in sorted(params.items()):
            if not isinstance(info, dict) or not info.get("writable"):
                continue
            record = spec.get(base + name)
            if not record:
                continue
            got = constraint_for(record)
            if got:
                entry[name] = got
        if entry:
            table[pattern] = entry
    return table, meta


def render(table, meta):
    return (HEADER
            + json.dumps(table, indent="\t", sort_keys=True) + ";\n\n"
            + OBJECT_HEADER
            + json.dumps(meta, indent="\t", sort_keys=True) + ";\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True, action="append",
                    help="schema_readable dump from dump-schema.uc; pass once "
                         "per protocol, because each drops the other's objects")
    ap.add_argument("--check", action="store_true",
                    help="report what would be written, write nothing")
    args = ap.parse_args()

    merged = {"objects": {}}
    for path in args.schema:
        doc = json.loads(Path(path).read_text())
        for pattern, params in (doc.get("objects") or {}).items():
            merged["objects"].setdefault(pattern, {}).update(params)

    table, meta = build(merged)
    text = render(table, meta)

    params = sum(len(v) for v in table.values())
    ro = sum(1 for v in meta.values() if v.get("addable") is False)
    tables = sum(1 for k in meta if k.endswith("{i}"))
    capped = sum(1 for v in meta.values() if "maxInstances" in v)
    print(f"{len(table)} object patterns, {params} writable parameters constrained")
    print(f"{len(meta)} objects with facts, {tables} of them tables, "
          f"{ro} not addable, {capped} with a finite maxInstances")
    print(f"{len(text)} bytes")

    if args.check:
        if OUT.exists() and OUT.read_text() == text:
            print("committed artefact is up to date")
            return 0
        print("committed artefact differs")
        return 1

    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
