#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
PROG=/usr/bin/dnsprobe

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -D
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "dnsprobe"
}

reload_service() {
	ubus call dnsprobe reload 2>/dev/null || restart
}
