#!/bin/sh /etc/rc.common

START=20
STOP=89

USE_PROCD=1
PROG=/usr/sbin/ubbf-container

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	ubus call ubbf-container reload '{}'
}

service_triggers() {
	procd_add_reload_trigger "containers"
}
