#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/ubbf-pcp

start_service() {
	[ -f /var/run/uci/pcp ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	restart
}

service_triggers() {
	procd_add_reload_trigger "pcp"
}
