function render_config() {
	const TESTBED_RPC_PORT = '7548';

	function testbed_rpc_rule(zone) {
		uci_section(output, 'firewall rule');
		uci_set_string(output, 'firewall.@rule[-1].name', `Allow-Testbed-RPC-${zone}`);
		uci_set_string(output, 'firewall.@rule[-1].src', zone);
		uci_set_string(output, 'firewall.@rule[-1].proto', 'tcp');
		uci_set_string(output, 'firewall.@rule[-1].dest_port', TESTBED_RPC_PORT);
		uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');
	}

	function upstream_zones() {
		let zones = [];

		for (let ifs in ubbf_instances(config, 'Device.Firewall.InterfaceSetting')) {
			if (!ubbf_to_bool(ifs.Enable))
				continue;
			if (!ubbf_to_bool(ubbf_get(config, ifs.Interface)?.Upstream))
				continue;

			let zone = interface_to_name(config, ifs.Interface);
			if (zone)
				push(zones, zone);
		}

		return uniq(zones);
	}

	// Rendered whatever the value, so a reader always finds the option and
	// a reset to the Test baseline renders the factory slot, or 0, instead
	// of leaving a stale slot.
	let testbed = {};
	include('factory.uc', { testbed });
	let slot = ubbf_to_int(ubbf_get(config, 'Device.X_UBBF.Testbed')?.Slot ??
			       testbed.factory_slot() ?? '0') ?? 0;
	uci_named_section(output, 'testbed.testbed', 'testbed');
	uci_set_number(output, 'testbed.testbed.slot', slot);

	// Every zone's input policy is REJECT and every reachable service
	// carries its own rule. The harness control port is rendered here so
	// it survives an apply, which rewrites the firewall config whole.
	// The DUT is driven from its LAN; an EasyMesh agent exposes no LAN to
	// the harness and is driven over its upstream interface.
	testbed_rpc_rule('lan');
	for (let zone in upstream_zones())
		testbed_rpc_rule(zone);
}
uci_comment(output, '# generated by testbed/render.uc');
render_config();
