'use strict';

import * as ubbf from 'ubbf';
import * as schemas from 'ubbf.schemas.Firewall';

const table_paths = {
	Service: 'Device.Firewall.Service',
	InterfaceSetting: 'Device.Firewall.InterfaceSetting',
	Policy: 'Device.Firewall.Policy'
};

const table_schemas = {
	Service: schemas.Service,
	InterfaceSetting: schemas.InterfaceSetting,
	Policy: schemas.Policy
};

/**
 * @param {object} existing - existing Service instance
 * @param {object} claim - descriptor from firewall hook
 * @returns {boolean} true if the existing entry covers the claim
 */
function service_matches(existing, claim) {
	if (existing.Interface != claim.Interface)
		return false;
	if (existing.Protocol != claim.Protocol)
		return false;
	if (existing.DestPort != claim.DestPort)
		return false;
	return true;
}

/**
 * @param {object} existing - existing InterfaceSetting instance
 * @param {object} claim - descriptor from firewall hook
 * @returns {boolean} true if the existing entry covers the claim
 */
function interface_setting_matches(existing, claim) {
	return existing.Interface == claim.Interface;
}

/**
 * @param {object} existing - existing Policy instance
 * @param {object} claim - descriptor from firewall hook
 * @returns {boolean} true if the existing entry covers the claim
 */
function policy_matches(existing, claim) {
	if (existing.SourceInterface != claim.SourceInterface)
		return false;
	if (existing.DestinationInterface != claim.DestinationInterface)
		return false;
	return true;
}

/**
 * Dispatches to the per-table match predicate for a given Firewall table.
 *
 * @param {string} table_type - 'Service', 'InterfaceSetting', or 'Policy'
 * @param {object} existing - existing instance entry
 * @param {object} claim - descriptor from a firewall hook
 * @returns {boolean} true if the existing entry covers the claim
 */
function entry_matches(table_type, existing, claim) {
	if (table_type == 'Service')
		return service_matches(existing, claim);
	if (table_type == 'InterfaceSetting')
		return interface_setting_matches(existing, claim);
	if (table_type == 'Policy')
		return policy_matches(existing, claim);
	return false;
}

/**
 * Tests whether an Alias was created by a model firewall hook (cpe- prefix).
 * Used to identify entries owned by reconcile so non-reconciled entries
 * (e.g. operator-defined) are preserved across passes.
 *
 * @param {string} alias - TR-181 Alias value
 * @returns {boolean} true if the alias was generated by reconcile
 */
function alias_is_cpe(alias) {
	if (!alias || alias == '')
		return false;
	return substr(alias, 0, 4) == 'cpe-';
}

/**
 * Collects firewall descriptors from all model entries with firewall hooks.
 *
 * @param {object} full_model - complete model definition
 * @param {object} data - config_data (Device root)
 * @returns {object} claims grouped by type: { Service: [], InterfaceSetting: [], Policy: [] }
 */
function claims_collect(full_model, data) {
	let claims = {
		Service: [],
		InterfaceSetting: [],
		Policy: []
	};

	for (let pattern in full_model) {
		let entry = full_model[pattern];
		if (!entry.firewall)
			continue;

		let pattern_parts = split(pattern, '.');
		let instance_paths = ubbf.collect_instances_for_pattern(
			pattern_parts, data, 0, '');

		for (let inst_path in instance_paths) {
			let inst_data = ubbf.navigate_data(data, split(inst_path, '.'));
			if (!inst_data)
				continue;

			let descriptors = entry.firewall(inst_data, data, inst_path);
			if (!descriptors)
				continue;

			for (let desc in descriptors) {
				if (!desc.type || !desc.alias)
					continue;
				if (!(desc.type in claims))
					continue;
				push(claims[desc.type], desc);
			}
		}
	}

	return claims;
}

/**
 * Reconciles a single Device.Firewall table against collected claims.
 *
 * @param {object} data - config_data root
 * @param {string} table_type - 'Service', 'InterfaceSetting', or 'Policy'
 * @param {array} type_claims - array of descriptor objects for this type
 */
function table_reconcile(data, table_type, type_claims) {
	let device = ubbf.navigate_or_create(data, ['Device']);
	let firewall = ubbf.navigate_or_create(device, ['Firewall']);
	let container = ubbf.navigate_or_create(firewall, [table_type]);

	let defaults = table_schemas[table_type]?.defaults ?? {};

	// Claims match existing entries by content, so the stale sweep must
	// key on the consumed container keys as well. Hook aliases are not
	// unique (two services can share one alias), so an alias-keyed sweep
	// both shields orphaned entries and deletes content-matched ones
	// whose alias scheme changed.
	let live_keys = {};

	for (let claim in type_claims) {
		let matched_key;

		for (let key, existing in container) {
			if (type(existing) != 'object')
				continue;
			if (!ubbf.is_instance_key(key))
				continue;

			if (!entry_matches(table_type, existing, claim))
				continue;

			matched_key = key;
			break;
		}

		if (matched_key != null) {
			let matched = container[matched_key];
			for (let k, v in defaults)
				if (!(k in matched))
					matched[k] = v;
			if (alias_is_cpe(matched.Alias))
				matched.Alias = claim.alias;
			live_keys[matched_key] = true;
			continue;
		}

		let inst_key = sprintf('%d', ubbf.find_next_instance(container));
		let new_entry = { ...defaults, Alias: claim.alias, Enable: 'true' };

		for (let attr_key, attr_val in claim) {
			if (attr_key == 'type' || attr_key == 'alias')
				continue;
			new_entry[attr_key] = attr_val;
		}

		container[inst_key] = new_entry;
		live_keys[inst_key] = true;
	}

	let stale = [];
	for (let key, existing in container) {
		if (type(existing) != 'object')
			continue;
		if (!ubbf.is_instance_key(key))
			continue;
		if (!alias_is_cpe(existing.Alias))
			continue;
		if (live_keys[key])
			continue;

		push(stale, key);
	}

	for (let key in stale)
		delete container[key];

	ubbf.entries_count_update(firewall, table_type, container);
}

/**
 * Runs the full firewall reconcile pass.
 *
 * @param {object} full_model - the complete model definition with firewall hooks
 * @param {object} data - config_data root (mutated in place)
 */
export function firewall_reconcile(full_model, data) {
	let claims = claims_collect(full_model, data);

	for (let table_type in table_paths)
		table_reconcile(data, table_type, claims[table_type]);
};
